// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "Generic.pb.h"
#import "User.pb.h"
#import "Product.pb.h"

@class AppSetting;
@class AppSetting_Builder;
@class Company;
@class Company_Builder;
@class Contact;
@class Contact_Builder;
@class Customer;
@class CustomerCategory;
@class CustomerCategory_Builder;
@class CustomerParams;
@class CustomerParams_Builder;
@class CustomerTag;
@class CustomerTagValue;
@class CustomerTagValue_Builder;
@class CustomerTag_Builder;
@class Customer_Builder;
@class Department;
@class Department_Builder;
@class Device;
@class Device_Builder;
@class Function;
@class Function_Builder;
@class Location;
@class Location_Builder;
@class PageCustomer;
@class PageCustomer_Builder;
@class PageUser;
@class PageUser_Builder;
@class Pagination;
@class Pagination_Builder;
@class Permission;
@class Permission_Builder;
@class Position;
@class Position_Builder;
@class Product;
@class ProductCategory;
@class ProductCategory_Builder;
@class ProductParams;
@class ProductParams_Builder;
@class ProductSpecification;
@class ProductSpecificationValue;
@class ProductSpecificationValue_Builder;
@class ProductSpecification_Builder;
@class Product_Builder;
@class SystemSetting;
@class SystemSetting_Builder;
@class User;
@class UserParams;
@class UserParams_Builder;
@class User_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface CustomerRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface Customer : PBGeneratedMessage {
@private
  BOOL hasIsFav_:1;
  BOOL hasId_:1;
  BOOL hasName_:1;
  BOOL hasSpell_:1;
  BOOL hasCountData_:1;
  BOOL hasHighLightName_:1;
  BOOL hasCategory_:1;
  BOOL hasLocation_:1;
  BOOL isFav_:1;
  int32_t id;
  NSString* name;
  NSString* spell;
  NSString* countData;
  NSString* highLightName;
  CustomerCategory* category;
  Location* location;
  PBAppendableArray * filePathArray;
  PBAppendableArray * contactsArray;
  PBAppendableArray * productsArray;
  PBAppendableArray * usersArray;
  PBAppendableArray * tagsArray;
  PBAppendableArray * filesArray;
}
- (BOOL) hasId;
- (BOOL) hasName;
- (BOOL) hasCategory;
- (BOOL) hasSpell;
- (BOOL) hasIsFav;
- (BOOL) hasLocation;
- (BOOL) hasCountData;
- (BOOL) hasHighLightName;
@property (readonly) int32_t id;
@property (readonly, retain) NSString* name;
@property (readonly, retain) CustomerCategory* category;
@property (readonly, retain) PBArray * contacts;
@property (readonly, retain) PBArray * products;
@property (readonly, retain) NSString* spell;
@property (readonly, retain) PBArray * users;
- (BOOL) isFav;
@property (readonly, retain) Location* location;
@property (readonly, retain) NSString* countData;
@property (readonly, retain) PBArray * files;
@property (readonly, retain) PBArray * filePath;
@property (readonly, retain) NSString* highLightName;
@property (readonly, retain) PBArray * tags;
- (Contact*)contactsAtIndex:(NSUInteger)index;
- (Product*)productsAtIndex:(NSUInteger)index;
- (User*)usersAtIndex:(NSUInteger)index;
- (NSData*)filesAtIndex:(NSUInteger)index;
- (NSString*)filePathAtIndex:(NSUInteger)index;
- (CustomerTag*)tagsAtIndex:(NSUInteger)index;

+ (Customer*) defaultInstance;
- (Customer*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Customer_Builder*) builder;
+ (Customer_Builder*) builder;
+ (Customer_Builder*) builderWithPrototype:(Customer*) prototype;
- (Customer_Builder*) toBuilder;

+ (Customer*) parseFromData:(NSData*) data;
+ (Customer*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Customer*) parseFromInputStream:(NSInputStream*) input;
+ (Customer*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Customer*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Customer*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Customer_Builder : PBGeneratedMessage_Builder {
@private
  Customer* result;
}

- (Customer*) defaultInstance;

- (Customer_Builder*) clear;
- (Customer_Builder*) clone;

- (Customer*) build;
- (Customer*) buildPartial;

- (Customer_Builder*) mergeFrom:(Customer*) other;
- (Customer_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Customer_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (int32_t) id;
- (Customer_Builder*) setId:(int32_t) value;
- (Customer_Builder*) clearId;

- (BOOL) hasName;
- (NSString*) name;
- (Customer_Builder*) setName:(NSString*) value;
- (Customer_Builder*) clearName;

- (BOOL) hasCategory;
- (CustomerCategory*) category;
- (Customer_Builder*) setCategory:(CustomerCategory*) value;
- (Customer_Builder*) setCategoryBuilder:(CustomerCategory_Builder*) builderForValue;
- (Customer_Builder*) mergeCategory:(CustomerCategory*) value;
- (Customer_Builder*) clearCategory;

- (PBAppendableArray *)contacts;
- (Contact*)contactsAtIndex:(NSUInteger)index;
- (Customer_Builder *)addContacts:(Contact*)value;
- (Customer_Builder *)setContactsArray:(NSArray *)array;
- (Customer_Builder *)setContactsValues:(const Contact* *)values count:(NSUInteger)count;
- (Customer_Builder *)clearContacts;

- (PBAppendableArray *)products;
- (Product*)productsAtIndex:(NSUInteger)index;
- (Customer_Builder *)addProducts:(Product*)value;
- (Customer_Builder *)setProductsArray:(NSArray *)array;
- (Customer_Builder *)setProductsValues:(const Product* *)values count:(NSUInteger)count;
- (Customer_Builder *)clearProducts;

- (BOOL) hasSpell;
- (NSString*) spell;
- (Customer_Builder*) setSpell:(NSString*) value;
- (Customer_Builder*) clearSpell;

- (PBAppendableArray *)users;
- (User*)usersAtIndex:(NSUInteger)index;
- (Customer_Builder *)addUsers:(User*)value;
- (Customer_Builder *)setUsersArray:(NSArray *)array;
- (Customer_Builder *)setUsersValues:(const User* *)values count:(NSUInteger)count;
- (Customer_Builder *)clearUsers;

- (BOOL) hasIsFav;
- (BOOL) isFav;
- (Customer_Builder*) setIsFav:(BOOL) value;
- (Customer_Builder*) clearIsFav;

- (BOOL) hasLocation;
- (Location*) location;
- (Customer_Builder*) setLocation:(Location*) value;
- (Customer_Builder*) setLocationBuilder:(Location_Builder*) builderForValue;
- (Customer_Builder*) mergeLocation:(Location*) value;
- (Customer_Builder*) clearLocation;

- (BOOL) hasCountData;
- (NSString*) countData;
- (Customer_Builder*) setCountData:(NSString*) value;
- (Customer_Builder*) clearCountData;

- (PBAppendableArray *)files;
- (NSData*)filesAtIndex:(NSUInteger)index;
- (Customer_Builder *)addFiles:(NSData*)value;
- (Customer_Builder *)setFilesArray:(NSArray *)array;
- (Customer_Builder *)setFilesValues:(const NSData* *)values count:(NSUInteger)count;
- (Customer_Builder *)clearFiles;

- (PBAppendableArray *)filePath;
- (NSString*)filePathAtIndex:(NSUInteger)index;
- (Customer_Builder *)addFilePath:(NSString*)value;
- (Customer_Builder *)setFilePathArray:(NSArray *)array;
- (Customer_Builder *)setFilePathValues:(const NSString* *)values count:(NSUInteger)count;
- (Customer_Builder *)clearFilePath;

- (BOOL) hasHighLightName;
- (NSString*) highLightName;
- (Customer_Builder*) setHighLightName:(NSString*) value;
- (Customer_Builder*) clearHighLightName;

- (PBAppendableArray *)tags;
- (CustomerTag*)tagsAtIndex:(NSUInteger)index;
- (Customer_Builder *)addTags:(CustomerTag*)value;
- (Customer_Builder *)setTagsArray:(NSArray *)array;
- (Customer_Builder *)setTagsValues:(const CustomerTag* *)values count:(NSUInteger)count;
- (Customer_Builder *)clearTags;
@end

@interface Contact : PBGeneratedMessage {
@private
  BOOL hasName_:1;
  NSString* name;
  PBAppendableArray * phoneArray;
}
- (BOOL) hasName;
@property (readonly, retain) NSString* name;
@property (readonly, retain) PBArray * phone;
- (NSString*)phoneAtIndex:(NSUInteger)index;

+ (Contact*) defaultInstance;
- (Contact*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Contact_Builder*) builder;
+ (Contact_Builder*) builder;
+ (Contact_Builder*) builderWithPrototype:(Contact*) prototype;
- (Contact_Builder*) toBuilder;

+ (Contact*) parseFromData:(NSData*) data;
+ (Contact*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Contact*) parseFromInputStream:(NSInputStream*) input;
+ (Contact*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Contact*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Contact*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Contact_Builder : PBGeneratedMessage_Builder {
@private
  Contact* result;
}

- (Contact*) defaultInstance;

- (Contact_Builder*) clear;
- (Contact_Builder*) clone;

- (Contact*) build;
- (Contact*) buildPartial;

- (Contact_Builder*) mergeFrom:(Contact*) other;
- (Contact_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Contact_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (Contact_Builder*) setName:(NSString*) value;
- (Contact_Builder*) clearName;

- (PBAppendableArray *)phone;
- (NSString*)phoneAtIndex:(NSUInteger)index;
- (Contact_Builder *)addPhone:(NSString*)value;
- (Contact_Builder *)setPhoneArray:(NSArray *)array;
- (Contact_Builder *)setPhoneValues:(const NSString* *)values count:(NSUInteger)count;
- (Contact_Builder *)clearPhone;
@end

@interface PageCustomer : PBGeneratedMessage {
@private
  BOOL hasPage_:1;
  Pagination* page;
  PBAppendableArray * customersArray;
}
- (BOOL) hasPage;
@property (readonly, retain) Pagination* page;
@property (readonly, retain) PBArray * customers;
- (Customer*)customersAtIndex:(NSUInteger)index;

+ (PageCustomer*) defaultInstance;
- (PageCustomer*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PageCustomer_Builder*) builder;
+ (PageCustomer_Builder*) builder;
+ (PageCustomer_Builder*) builderWithPrototype:(PageCustomer*) prototype;
- (PageCustomer_Builder*) toBuilder;

+ (PageCustomer*) parseFromData:(NSData*) data;
+ (PageCustomer*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PageCustomer*) parseFromInputStream:(NSInputStream*) input;
+ (PageCustomer*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PageCustomer*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PageCustomer*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PageCustomer_Builder : PBGeneratedMessage_Builder {
@private
  PageCustomer* result;
}

- (PageCustomer*) defaultInstance;

- (PageCustomer_Builder*) clear;
- (PageCustomer_Builder*) clone;

- (PageCustomer*) build;
- (PageCustomer*) buildPartial;

- (PageCustomer_Builder*) mergeFrom:(PageCustomer*) other;
- (PageCustomer_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PageCustomer_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPage;
- (Pagination*) page;
- (PageCustomer_Builder*) setPage:(Pagination*) value;
- (PageCustomer_Builder*) setPageBuilder:(Pagination_Builder*) builderForValue;
- (PageCustomer_Builder*) mergePage:(Pagination*) value;
- (PageCustomer_Builder*) clearPage;

- (PBAppendableArray *)customers;
- (Customer*)customersAtIndex:(NSUInteger)index;
- (PageCustomer_Builder *)addCustomers:(Customer*)value;
- (PageCustomer_Builder *)setCustomersArray:(NSArray *)array;
- (PageCustomer_Builder *)setCustomersValues:(const Customer* *)values count:(NSUInteger)count;
- (PageCustomer_Builder *)clearCustomers;
@end

@interface CustomerParams : PBGeneratedMessage {
@private
  BOOL hasTag_:1;
  BOOL hasPage_:1;
  BOOL hasUser_:1;
  BOOL hasCustomer_:1;
  BOOL hasLocation_:1;
  BOOL hasCategory_:1;
  BOOL tag_:1;
  int32_t page;
  User* user;
  Customer* customer;
  Location* location;
  CustomerCategory* category;
  PBAppendableArray * tagValuesArray;
}
- (BOOL) hasPage;
- (BOOL) hasUser;
- (BOOL) hasCustomer;
- (BOOL) hasLocation;
- (BOOL) hasCategory;
- (BOOL) hasTag;
@property (readonly) int32_t page;
@property (readonly, retain) User* user;
@property (readonly, retain) Customer* customer;
@property (readonly, retain) Location* location;
@property (readonly, retain) CustomerCategory* category;
- (BOOL) tag;
@property (readonly, retain) PBArray * tagValues;
- (CustomerTagValue*)tagValuesAtIndex:(NSUInteger)index;

+ (CustomerParams*) defaultInstance;
- (CustomerParams*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CustomerParams_Builder*) builder;
+ (CustomerParams_Builder*) builder;
+ (CustomerParams_Builder*) builderWithPrototype:(CustomerParams*) prototype;
- (CustomerParams_Builder*) toBuilder;

+ (CustomerParams*) parseFromData:(NSData*) data;
+ (CustomerParams*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CustomerParams*) parseFromInputStream:(NSInputStream*) input;
+ (CustomerParams*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CustomerParams*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CustomerParams*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CustomerParams_Builder : PBGeneratedMessage_Builder {
@private
  CustomerParams* result;
}

- (CustomerParams*) defaultInstance;

- (CustomerParams_Builder*) clear;
- (CustomerParams_Builder*) clone;

- (CustomerParams*) build;
- (CustomerParams*) buildPartial;

- (CustomerParams_Builder*) mergeFrom:(CustomerParams*) other;
- (CustomerParams_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CustomerParams_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPage;
- (int32_t) page;
- (CustomerParams_Builder*) setPage:(int32_t) value;
- (CustomerParams_Builder*) clearPage;

- (BOOL) hasUser;
- (User*) user;
- (CustomerParams_Builder*) setUser:(User*) value;
- (CustomerParams_Builder*) setUserBuilder:(User_Builder*) builderForValue;
- (CustomerParams_Builder*) mergeUser:(User*) value;
- (CustomerParams_Builder*) clearUser;

- (BOOL) hasCustomer;
- (Customer*) customer;
- (CustomerParams_Builder*) setCustomer:(Customer*) value;
- (CustomerParams_Builder*) setCustomerBuilder:(Customer_Builder*) builderForValue;
- (CustomerParams_Builder*) mergeCustomer:(Customer*) value;
- (CustomerParams_Builder*) clearCustomer;

- (BOOL) hasLocation;
- (Location*) location;
- (CustomerParams_Builder*) setLocation:(Location*) value;
- (CustomerParams_Builder*) setLocationBuilder:(Location_Builder*) builderForValue;
- (CustomerParams_Builder*) mergeLocation:(Location*) value;
- (CustomerParams_Builder*) clearLocation;

- (BOOL) hasCategory;
- (CustomerCategory*) category;
- (CustomerParams_Builder*) setCategory:(CustomerCategory*) value;
- (CustomerParams_Builder*) setCategoryBuilder:(CustomerCategory_Builder*) builderForValue;
- (CustomerParams_Builder*) mergeCategory:(CustomerCategory*) value;
- (CustomerParams_Builder*) clearCategory;

- (BOOL) hasTag;
- (BOOL) tag;
- (CustomerParams_Builder*) setTag:(BOOL) value;
- (CustomerParams_Builder*) clearTag;

- (PBAppendableArray *)tagValues;
- (CustomerTagValue*)tagValuesAtIndex:(NSUInteger)index;
- (CustomerParams_Builder *)addTagValues:(CustomerTagValue*)value;
- (CustomerParams_Builder *)setTagValuesArray:(NSArray *)array;
- (CustomerParams_Builder *)setTagValuesValues:(const CustomerTagValue* *)values count:(NSUInteger)count;
- (CustomerParams_Builder *)clearTagValues;
@end

@interface CustomerCategory : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasName_:1;
  int32_t id;
  NSString* name;
}
- (BOOL) hasName;
- (BOOL) hasId;
@property (readonly, retain) NSString* name;
@property (readonly) int32_t id;

+ (CustomerCategory*) defaultInstance;
- (CustomerCategory*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CustomerCategory_Builder*) builder;
+ (CustomerCategory_Builder*) builder;
+ (CustomerCategory_Builder*) builderWithPrototype:(CustomerCategory*) prototype;
- (CustomerCategory_Builder*) toBuilder;

+ (CustomerCategory*) parseFromData:(NSData*) data;
+ (CustomerCategory*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CustomerCategory*) parseFromInputStream:(NSInputStream*) input;
+ (CustomerCategory*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CustomerCategory*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CustomerCategory*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CustomerCategory_Builder : PBGeneratedMessage_Builder {
@private
  CustomerCategory* result;
}

- (CustomerCategory*) defaultInstance;

- (CustomerCategory_Builder*) clear;
- (CustomerCategory_Builder*) clone;

- (CustomerCategory*) build;
- (CustomerCategory*) buildPartial;

- (CustomerCategory_Builder*) mergeFrom:(CustomerCategory*) other;
- (CustomerCategory_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CustomerCategory_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (CustomerCategory_Builder*) setName:(NSString*) value;
- (CustomerCategory_Builder*) clearName;

- (BOOL) hasId;
- (int32_t) id;
- (CustomerCategory_Builder*) setId:(int32_t) value;
- (CustomerCategory_Builder*) clearId;
@end

@interface CustomerTag : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasName_:1;
  int32_t id;
  NSString* name;
  PBAppendableArray * tagValuesArray;
}
- (BOOL) hasName;
- (BOOL) hasId;
@property (readonly, retain) NSString* name;
@property (readonly) int32_t id;
@property (readonly, retain) PBArray * tagValues;
- (CustomerTagValue*)tagValuesAtIndex:(NSUInteger)index;

+ (CustomerTag*) defaultInstance;
- (CustomerTag*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CustomerTag_Builder*) builder;
+ (CustomerTag_Builder*) builder;
+ (CustomerTag_Builder*) builderWithPrototype:(CustomerTag*) prototype;
- (CustomerTag_Builder*) toBuilder;

+ (CustomerTag*) parseFromData:(NSData*) data;
+ (CustomerTag*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CustomerTag*) parseFromInputStream:(NSInputStream*) input;
+ (CustomerTag*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CustomerTag*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CustomerTag*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CustomerTag_Builder : PBGeneratedMessage_Builder {
@private
  CustomerTag* result;
}

- (CustomerTag*) defaultInstance;

- (CustomerTag_Builder*) clear;
- (CustomerTag_Builder*) clone;

- (CustomerTag*) build;
- (CustomerTag*) buildPartial;

- (CustomerTag_Builder*) mergeFrom:(CustomerTag*) other;
- (CustomerTag_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CustomerTag_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (CustomerTag_Builder*) setName:(NSString*) value;
- (CustomerTag_Builder*) clearName;

- (BOOL) hasId;
- (int32_t) id;
- (CustomerTag_Builder*) setId:(int32_t) value;
- (CustomerTag_Builder*) clearId;

- (PBAppendableArray *)tagValues;
- (CustomerTagValue*)tagValuesAtIndex:(NSUInteger)index;
- (CustomerTag_Builder *)addTagValues:(CustomerTagValue*)value;
- (CustomerTag_Builder *)setTagValuesArray:(NSArray *)array;
- (CustomerTag_Builder *)setTagValuesValues:(const CustomerTagValue* *)values count:(NSUInteger)count;
- (CustomerTag_Builder *)clearTagValues;
@end

@interface CustomerTagValue : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasParentId_:1;
  BOOL hasName_:1;
  BOOL hasPath_:1;
  int32_t id;
  int32_t parentId;
  NSString* name;
  NSString* path;
}
- (BOOL) hasName;
- (BOOL) hasId;
- (BOOL) hasParentId;
- (BOOL) hasPath;
@property (readonly, retain) NSString* name;
@property (readonly) int32_t id;
@property (readonly) int32_t parentId;
@property (readonly, retain) NSString* path;

+ (CustomerTagValue*) defaultInstance;
- (CustomerTagValue*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CustomerTagValue_Builder*) builder;
+ (CustomerTagValue_Builder*) builder;
+ (CustomerTagValue_Builder*) builderWithPrototype:(CustomerTagValue*) prototype;
- (CustomerTagValue_Builder*) toBuilder;

+ (CustomerTagValue*) parseFromData:(NSData*) data;
+ (CustomerTagValue*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CustomerTagValue*) parseFromInputStream:(NSInputStream*) input;
+ (CustomerTagValue*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CustomerTagValue*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CustomerTagValue*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CustomerTagValue_Builder : PBGeneratedMessage_Builder {
@private
  CustomerTagValue* result;
}

- (CustomerTagValue*) defaultInstance;

- (CustomerTagValue_Builder*) clear;
- (CustomerTagValue_Builder*) clone;

- (CustomerTagValue*) build;
- (CustomerTagValue*) buildPartial;

- (CustomerTagValue_Builder*) mergeFrom:(CustomerTagValue*) other;
- (CustomerTagValue_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CustomerTagValue_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (CustomerTagValue_Builder*) setName:(NSString*) value;
- (CustomerTagValue_Builder*) clearName;

- (BOOL) hasId;
- (int32_t) id;
- (CustomerTagValue_Builder*) setId:(int32_t) value;
- (CustomerTagValue_Builder*) clearId;

- (BOOL) hasParentId;
- (int32_t) parentId;
- (CustomerTagValue_Builder*) setParentId:(int32_t) value;
- (CustomerTagValue_Builder*) clearParentId;

- (BOOL) hasPath;
- (NSString*) path;
- (CustomerTagValue_Builder*) setPath:(NSString*) value;
- (CustomerTagValue_Builder*) clearPath;
@end

