// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "User.pb.h"

@class AppSetting;
@class AppSetting_Builder;
@class Company;
@class Company_Builder;
@class Department;
@class Department_Builder;
@class Device;
@class Device_Builder;
@class FavoriteLang;
@class FavoriteLang_Builder;
@class Function;
@class Function_Builder;
@class Location;
@class Location_Builder;
@class PageUser;
@class PageUser_Builder;
@class Pagination;
@class Pagination_Builder;
@class Permission;
@class Permission_Builder;
@class Position;
@class Position_Builder;
@class SystemSetting;
@class SystemSetting_Builder;
@class User;
@class UserParams;
@class UserParams_Builder;
@class User_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface FavoriteLangRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface FavoriteLang : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasCommonLang_:1;
  BOOL hasUser_:1;
  int32_t id;
  NSString* commonLang;
  User* user;
}
- (BOOL) hasId;
- (BOOL) hasUser;
- (BOOL) hasCommonLang;
@property (readonly) int32_t id;
@property (readonly, retain) User* user;
@property (readonly, retain) NSString* commonLang;

+ (FavoriteLang*) defaultInstance;
- (FavoriteLang*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FavoriteLang_Builder*) builder;
+ (FavoriteLang_Builder*) builder;
+ (FavoriteLang_Builder*) builderWithPrototype:(FavoriteLang*) prototype;
- (FavoriteLang_Builder*) toBuilder;

+ (FavoriteLang*) parseFromData:(NSData*) data;
+ (FavoriteLang*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FavoriteLang*) parseFromInputStream:(NSInputStream*) input;
+ (FavoriteLang*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FavoriteLang*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FavoriteLang*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FavoriteLang_Builder : PBGeneratedMessage_Builder {
@private
  FavoriteLang* result;
}

- (FavoriteLang*) defaultInstance;

- (FavoriteLang_Builder*) clear;
- (FavoriteLang_Builder*) clone;

- (FavoriteLang*) build;
- (FavoriteLang*) buildPartial;

- (FavoriteLang_Builder*) mergeFrom:(FavoriteLang*) other;
- (FavoriteLang_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FavoriteLang_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (int32_t) id;
- (FavoriteLang_Builder*) setId:(int32_t) value;
- (FavoriteLang_Builder*) clearId;

- (BOOL) hasUser;
- (User*) user;
- (FavoriteLang_Builder*) setUser:(User*) value;
- (FavoriteLang_Builder*) setUserBuilder:(User_Builder*) builderForValue;
- (FavoriteLang_Builder*) mergeUser:(User*) value;
- (FavoriteLang_Builder*) clearUser;

- (BOOL) hasCommonLang;
- (NSString*) commonLang;
- (FavoriteLang_Builder*) setCommonLang:(NSString*) value;
- (FavoriteLang_Builder*) clearCommonLang;
@end

