// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class AppSetting;
@class AppSetting_Builder;
@class Function;
@class Function_Builder;
@class Location;
@class Location_Builder;
@class Pagination;
@class Pagination_Builder;
@class SystemSetting;
@class SystemSetting_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface GenericRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface Pagination : PBGeneratedMessage {
@private
  BOOL hasTotalSize_:1;
  BOOL hasPage_:1;
  BOOL hasPageSize_:1;
  int64_t totalSize;
  int32_t page;
  int32_t pageSize;
  PBAppendableArray * datasArray;
}
- (BOOL) hasPage;
- (BOOL) hasPageSize;
- (BOOL) hasTotalSize;
@property (readonly) int32_t page;
@property (readonly) int32_t pageSize;
@property (readonly) int64_t totalSize;
@property (readonly, retain) PBArray * datas;
- (NSData*)datasAtIndex:(NSUInteger)index;

+ (Pagination*) defaultInstance;
- (Pagination*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Pagination_Builder*) builder;
+ (Pagination_Builder*) builder;
+ (Pagination_Builder*) builderWithPrototype:(Pagination*) prototype;
- (Pagination_Builder*) toBuilder;

+ (Pagination*) parseFromData:(NSData*) data;
+ (Pagination*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Pagination*) parseFromInputStream:(NSInputStream*) input;
+ (Pagination*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Pagination*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Pagination*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Pagination_Builder : PBGeneratedMessage_Builder {
@private
  Pagination* result;
}

- (Pagination*) defaultInstance;

- (Pagination_Builder*) clear;
- (Pagination_Builder*) clone;

- (Pagination*) build;
- (Pagination*) buildPartial;

- (Pagination_Builder*) mergeFrom:(Pagination*) other;
- (Pagination_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Pagination_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPage;
- (int32_t) page;
- (Pagination_Builder*) setPage:(int32_t) value;
- (Pagination_Builder*) clearPage;

- (BOOL) hasPageSize;
- (int32_t) pageSize;
- (Pagination_Builder*) setPageSize:(int32_t) value;
- (Pagination_Builder*) clearPageSize;

- (BOOL) hasTotalSize;
- (int64_t) totalSize;
- (Pagination_Builder*) setTotalSize:(int64_t) value;
- (Pagination_Builder*) clearTotalSize;

- (PBAppendableArray *)datas;
- (NSData*)datasAtIndex:(NSUInteger)index;
- (Pagination_Builder *)addDatas:(NSData*)value;
- (Pagination_Builder *)setDatasArray:(NSArray *)array;
- (Pagination_Builder *)setDatasValues:(const NSData* *)values count:(NSUInteger)count;
- (Pagination_Builder *)clearDatas;
@end

@interface Location : PBGeneratedMessage {
@private
  BOOL hasLatitude_:1;
  BOOL hasLongitude_:1;
  BOOL hasId_:1;
  BOOL hasVersion_:1;
  BOOL hasAddress_:1;
  BOOL hasProvince_:1;
  BOOL hasCity_:1;
  BOOL hasDistrict_:1;
  BOOL hasDistance_:1;
  BOOL hasCreateTime_:1;
  BOOL hasProvinceCode_:1;
  BOOL hasCityCode_:1;
  BOOL hasDistrictCode_:1;
  Float64 latitude;
  Float64 longitude;
  int32_t id;
  int32_t version;
  NSString* address;
  NSString* province;
  NSString* city;
  NSString* district;
  NSString* distance;
  NSString* createTime;
  NSString* provinceCode;
  NSString* cityCode;
  NSString* districtCode;
}
- (BOOL) hasId;
- (BOOL) hasLatitude;
- (BOOL) hasLongitude;
- (BOOL) hasAddress;
- (BOOL) hasProvince;
- (BOOL) hasCity;
- (BOOL) hasDistrict;
- (BOOL) hasDistance;
- (BOOL) hasCreateTime;
- (BOOL) hasVersion;
- (BOOL) hasProvinceCode;
- (BOOL) hasCityCode;
- (BOOL) hasDistrictCode;
@property (readonly) int32_t id;
@property (readonly) Float64 latitude;
@property (readonly) Float64 longitude;
@property (readonly, retain) NSString* address;
@property (readonly, retain) NSString* province;
@property (readonly, retain) NSString* city;
@property (readonly, retain) NSString* district;
@property (readonly, retain) NSString* distance;
@property (readonly, retain) NSString* createTime;
@property (readonly) int32_t version;
@property (readonly, retain) NSString* provinceCode;
@property (readonly, retain) NSString* cityCode;
@property (readonly, retain) NSString* districtCode;

+ (Location*) defaultInstance;
- (Location*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Location_Builder*) builder;
+ (Location_Builder*) builder;
+ (Location_Builder*) builderWithPrototype:(Location*) prototype;
- (Location_Builder*) toBuilder;

+ (Location*) parseFromData:(NSData*) data;
+ (Location*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Location*) parseFromInputStream:(NSInputStream*) input;
+ (Location*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Location*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Location*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Location_Builder : PBGeneratedMessage_Builder {
@private
  Location* result;
}

- (Location*) defaultInstance;

- (Location_Builder*) clear;
- (Location_Builder*) clone;

- (Location*) build;
- (Location*) buildPartial;

- (Location_Builder*) mergeFrom:(Location*) other;
- (Location_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Location_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (int32_t) id;
- (Location_Builder*) setId:(int32_t) value;
- (Location_Builder*) clearId;

- (BOOL) hasLatitude;
- (Float64) latitude;
- (Location_Builder*) setLatitude:(Float64) value;
- (Location_Builder*) clearLatitude;

- (BOOL) hasLongitude;
- (Float64) longitude;
- (Location_Builder*) setLongitude:(Float64) value;
- (Location_Builder*) clearLongitude;

- (BOOL) hasAddress;
- (NSString*) address;
- (Location_Builder*) setAddress:(NSString*) value;
- (Location_Builder*) clearAddress;

- (BOOL) hasProvince;
- (NSString*) province;
- (Location_Builder*) setProvince:(NSString*) value;
- (Location_Builder*) clearProvince;

- (BOOL) hasCity;
- (NSString*) city;
- (Location_Builder*) setCity:(NSString*) value;
- (Location_Builder*) clearCity;

- (BOOL) hasDistrict;
- (NSString*) district;
- (Location_Builder*) setDistrict:(NSString*) value;
- (Location_Builder*) clearDistrict;

- (BOOL) hasDistance;
- (NSString*) distance;
- (Location_Builder*) setDistance:(NSString*) value;
- (Location_Builder*) clearDistance;

- (BOOL) hasCreateTime;
- (NSString*) createTime;
- (Location_Builder*) setCreateTime:(NSString*) value;
- (Location_Builder*) clearCreateTime;

- (BOOL) hasVersion;
- (int32_t) version;
- (Location_Builder*) setVersion:(int32_t) value;
- (Location_Builder*) clearVersion;

- (BOOL) hasProvinceCode;
- (NSString*) provinceCode;
- (Location_Builder*) setProvinceCode:(NSString*) value;
- (Location_Builder*) clearProvinceCode;

- (BOOL) hasCityCode;
- (NSString*) cityCode;
- (Location_Builder*) setCityCode:(NSString*) value;
- (Location_Builder*) clearCityCode;

- (BOOL) hasDistrictCode;
- (NSString*) districtCode;
- (Location_Builder*) setDistrictCode:(NSString*) value;
- (Location_Builder*) clearDistrictCode;
@end

@interface SystemSetting : PBGeneratedMessage {
@private
  BOOL hasLocationInterval_:1;
  BOOL hasCustomerTagQueryMax_:1;
  BOOL hasCustomerTagValQueryMax_:1;
  BOOL hasProdSpecQueryMax_:1;
  BOOL hasProdSpecValQueryMax_:1;
  int32_t locationInterval;
  int32_t customerTagQueryMax;
  int32_t customerTagValQueryMax;
  int32_t prodSpecQueryMax;
  int32_t prodSpecValQueryMax;
}
- (BOOL) hasLocationInterval;
- (BOOL) hasCustomerTagQueryMax;
- (BOOL) hasCustomerTagValQueryMax;
- (BOOL) hasProdSpecQueryMax;
- (BOOL) hasProdSpecValQueryMax;
@property (readonly) int32_t locationInterval;
@property (readonly) int32_t customerTagQueryMax;
@property (readonly) int32_t customerTagValQueryMax;
@property (readonly) int32_t prodSpecQueryMax;
@property (readonly) int32_t prodSpecValQueryMax;

+ (SystemSetting*) defaultInstance;
- (SystemSetting*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SystemSetting_Builder*) builder;
+ (SystemSetting_Builder*) builder;
+ (SystemSetting_Builder*) builderWithPrototype:(SystemSetting*) prototype;
- (SystemSetting_Builder*) toBuilder;

+ (SystemSetting*) parseFromData:(NSData*) data;
+ (SystemSetting*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SystemSetting*) parseFromInputStream:(NSInputStream*) input;
+ (SystemSetting*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SystemSetting*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SystemSetting*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SystemSetting_Builder : PBGeneratedMessage_Builder {
@private
  SystemSetting* result;
}

- (SystemSetting*) defaultInstance;

- (SystemSetting_Builder*) clear;
- (SystemSetting_Builder*) clone;

- (SystemSetting*) build;
- (SystemSetting*) buildPartial;

- (SystemSetting_Builder*) mergeFrom:(SystemSetting*) other;
- (SystemSetting_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SystemSetting_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasLocationInterval;
- (int32_t) locationInterval;
- (SystemSetting_Builder*) setLocationInterval:(int32_t) value;
- (SystemSetting_Builder*) clearLocationInterval;

- (BOOL) hasCustomerTagQueryMax;
- (int32_t) customerTagQueryMax;
- (SystemSetting_Builder*) setCustomerTagQueryMax:(int32_t) value;
- (SystemSetting_Builder*) clearCustomerTagQueryMax;

- (BOOL) hasCustomerTagValQueryMax;
- (int32_t) customerTagValQueryMax;
- (SystemSetting_Builder*) setCustomerTagValQueryMax:(int32_t) value;
- (SystemSetting_Builder*) clearCustomerTagValQueryMax;

- (BOOL) hasProdSpecQueryMax;
- (int32_t) prodSpecQueryMax;
- (SystemSetting_Builder*) setProdSpecQueryMax:(int32_t) value;
- (SystemSetting_Builder*) clearProdSpecQueryMax;

- (BOOL) hasProdSpecValQueryMax;
- (int32_t) prodSpecValQueryMax;
- (SystemSetting_Builder*) setProdSpecValQueryMax:(int32_t) value;
- (SystemSetting_Builder*) clearProdSpecValQueryMax;
@end

@interface AppSetting : PBGeneratedMessage {
@private
  BOOL hasAppTitle_:1;
  NSString* appTitle;
}
- (BOOL) hasAppTitle;
@property (readonly, retain) NSString* appTitle;

+ (AppSetting*) defaultInstance;
- (AppSetting*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AppSetting_Builder*) builder;
+ (AppSetting_Builder*) builder;
+ (AppSetting_Builder*) builderWithPrototype:(AppSetting*) prototype;
- (AppSetting_Builder*) toBuilder;

+ (AppSetting*) parseFromData:(NSData*) data;
+ (AppSetting*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppSetting*) parseFromInputStream:(NSInputStream*) input;
+ (AppSetting*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppSetting*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AppSetting*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AppSetting_Builder : PBGeneratedMessage_Builder {
@private
  AppSetting* result;
}

- (AppSetting*) defaultInstance;

- (AppSetting_Builder*) clear;
- (AppSetting_Builder*) clone;

- (AppSetting*) build;
- (AppSetting*) buildPartial;

- (AppSetting_Builder*) mergeFrom:(AppSetting*) other;
- (AppSetting_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AppSetting_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasAppTitle;
- (NSString*) appTitle;
- (AppSetting_Builder*) setAppTitle:(NSString*) value;
- (AppSetting_Builder*) clearAppTitle;
@end

@interface Function : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasName_:1;
  BOOL hasValue_:1;
  int32_t id;
  NSString* name;
  NSString* value;
}
- (BOOL) hasId;
- (BOOL) hasName;
- (BOOL) hasValue;
@property (readonly) int32_t id;
@property (readonly, retain) NSString* name;
@property (readonly, retain) NSString* value;

+ (Function*) defaultInstance;
- (Function*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Function_Builder*) builder;
+ (Function_Builder*) builder;
+ (Function_Builder*) builderWithPrototype:(Function*) prototype;
- (Function_Builder*) toBuilder;

+ (Function*) parseFromData:(NSData*) data;
+ (Function*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Function*) parseFromInputStream:(NSInputStream*) input;
+ (Function*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Function*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Function*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Function_Builder : PBGeneratedMessage_Builder {
@private
  Function* result;
}

- (Function*) defaultInstance;

- (Function_Builder*) clear;
- (Function_Builder*) clone;

- (Function*) build;
- (Function*) buildPartial;

- (Function_Builder*) mergeFrom:(Function*) other;
- (Function_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Function_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (int32_t) id;
- (Function_Builder*) setId:(int32_t) value;
- (Function_Builder*) clearId;

- (BOOL) hasName;
- (NSString*) name;
- (Function_Builder*) setName:(NSString*) value;
- (Function_Builder*) clearName;

- (BOOL) hasValue;
- (NSString*) value;
- (Function_Builder*) setValue:(NSString*) value;
- (Function_Builder*) clearValue;
@end

