// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Print.pb.h"

@implementation PrintRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [PrintRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    [UserRoot registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface Print ()
@property (retain) NSString* content;
@end

@implementation Print

- (BOOL) hasContent {
  return !!hasContent_;
}
- (void) setHasContent:(BOOL) value_ {
  hasContent_ = !!value_;
}
@synthesize content;
- (void) dealloc {
  self.content = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.content = @"";
  }
  return self;
}
static Print* defaultPrintInstance = nil;
+ (void) initialize {
  if (self == [Print class]) {
    defaultPrintInstance = [[Print alloc] init];
  }
}
+ (Print*) defaultInstance {
  return defaultPrintInstance;
}
- (Print*) defaultInstance {
  return defaultPrintInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasContent) {
    [output writeString:1 value:self.content];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasContent) {
    size_ += computeStringSize(1, self.content);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (Print*) parseFromData:(NSData*) data {
  return (Print*)[[[Print builder] mergeFromData:data] build];
}
+ (Print*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Print*)[[[Print builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (Print*) parseFromInputStream:(NSInputStream*) input {
  return (Print*)[[[Print builder] mergeFromInputStream:input] build];
}
+ (Print*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Print*)[[[Print builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Print*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (Print*)[[[Print builder] mergeFromCodedInputStream:input] build];
}
+ (Print*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Print*)[[[Print builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Print_Builder*) builder {
  return [[[Print_Builder alloc] init] autorelease];
}
+ (Print_Builder*) builderWithPrototype:(Print*) prototype {
  return [[Print builder] mergeFrom:prototype];
}
- (Print_Builder*) builder {
  return [Print builder];
}
- (Print_Builder*) toBuilder {
  return [Print builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasContent) {
    [output appendFormat:@"%@%@: %@\n", indent, @"content", self.content];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[Print class]]) {
    return NO;
  }
  Print *otherMessage = other;
  return
      self.hasContent == otherMessage.hasContent &&
      (!self.hasContent || [self.content isEqual:otherMessage.content]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  NSUInteger hashCode = 7;
  if (self.hasContent) {
    hashCode = hashCode * 31 + [self.content hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface Print_Builder()
@property (retain) Print* result;
@end

@implementation Print_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[Print alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (Print_Builder*) clear {
  self.result = [[[Print alloc] init] autorelease];
  return self;
}
- (Print_Builder*) clone {
  return [Print builderWithPrototype:result];
}
- (Print*) defaultInstance {
  return [Print defaultInstance];
}
- (Print*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (Print*) buildPartial {
  Print* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (Print_Builder*) mergeFrom:(Print*) other {
  if (other == [Print defaultInstance]) {
    return self;
  }
  if (other.hasContent) {
    [self setContent:other.content];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (Print_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (Print_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setContent:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasContent {
  return result.hasContent;
}
- (NSString*) content {
  return result.content;
}
- (Print_Builder*) setContent:(NSString*) value {
  result.hasContent = YES;
  result.content = value;
  return self;
}
- (Print_Builder*) clearContent {
  result.hasContent = NO;
  result.content = @"";
  return self;
}
@end

@interface PrintParams ()
@property int32_t orderId;
@end

@implementation PrintParams

- (BOOL) hasOrderId {
  return !!hasOrderId_;
}
- (void) setHasOrderId:(BOOL) value_ {
  hasOrderId_ = !!value_;
}
@synthesize orderId;
- (void) dealloc {
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.orderId = 0;
  }
  return self;
}
static PrintParams* defaultPrintParamsInstance = nil;
+ (void) initialize {
  if (self == [PrintParams class]) {
    defaultPrintParamsInstance = [[PrintParams alloc] init];
  }
}
+ (PrintParams*) defaultInstance {
  return defaultPrintParamsInstance;
}
- (PrintParams*) defaultInstance {
  return defaultPrintParamsInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasOrderId) {
    [output writeInt32:1 value:self.orderId];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasOrderId) {
    size_ += computeInt32Size(1, self.orderId);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (PrintParams*) parseFromData:(NSData*) data {
  return (PrintParams*)[[[PrintParams builder] mergeFromData:data] build];
}
+ (PrintParams*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PrintParams*)[[[PrintParams builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (PrintParams*) parseFromInputStream:(NSInputStream*) input {
  return (PrintParams*)[[[PrintParams builder] mergeFromInputStream:input] build];
}
+ (PrintParams*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PrintParams*)[[[PrintParams builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PrintParams*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (PrintParams*)[[[PrintParams builder] mergeFromCodedInputStream:input] build];
}
+ (PrintParams*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PrintParams*)[[[PrintParams builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PrintParams_Builder*) builder {
  return [[[PrintParams_Builder alloc] init] autorelease];
}
+ (PrintParams_Builder*) builderWithPrototype:(PrintParams*) prototype {
  return [[PrintParams builder] mergeFrom:prototype];
}
- (PrintParams_Builder*) builder {
  return [PrintParams builder];
}
- (PrintParams_Builder*) toBuilder {
  return [PrintParams builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasOrderId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"orderId", [NSNumber numberWithInt:self.orderId]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[PrintParams class]]) {
    return NO;
  }
  PrintParams *otherMessage = other;
  return
      self.hasOrderId == otherMessage.hasOrderId &&
      (!self.hasOrderId || self.orderId == otherMessage.orderId) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  NSUInteger hashCode = 7;
  if (self.hasOrderId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.orderId] hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface PrintParams_Builder()
@property (retain) PrintParams* result;
@end

@implementation PrintParams_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[PrintParams alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (PrintParams_Builder*) clear {
  self.result = [[[PrintParams alloc] init] autorelease];
  return self;
}
- (PrintParams_Builder*) clone {
  return [PrintParams builderWithPrototype:result];
}
- (PrintParams*) defaultInstance {
  return [PrintParams defaultInstance];
}
- (PrintParams*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (PrintParams*) buildPartial {
  PrintParams* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (PrintParams_Builder*) mergeFrom:(PrintParams*) other {
  if (other == [PrintParams defaultInstance]) {
    return self;
  }
  if (other.hasOrderId) {
    [self setOrderId:other.orderId];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (PrintParams_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (PrintParams_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setOrderId:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasOrderId {
  return result.hasOrderId;
}
- (int32_t) orderId {
  return result.orderId;
}
- (PrintParams_Builder*) setOrderId:(int32_t) value {
  result.hasOrderId = YES;
  result.orderId = value;
  return self;
}
- (PrintParams_Builder*) clearOrderId {
  result.hasOrderId = NO;
  result.orderId = 0;
  return self;
}
@end

