// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class Product;
@class ProductCategory;
@class ProductCategory_Builder;
@class ProductParams;
@class ProductParams_Builder;
@class ProductSpecification;
@class ProductSpecificationValue;
@class ProductSpecificationValue_Builder;
@class ProductSpecification_Builder;
@class Product_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif

typedef enum {
  PriceSortAsc = 1,
  PriceSortDes = 2,
} PriceSort;

BOOL PriceSortIsValidValue(PriceSort value);


@interface ProductRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface Product : PBGeneratedMessage {
@private
  BOOL hasIsFav_:1;
  BOOL hasNum_:1;
  BOOL hasPrice_:1;
  BOOL hasId_:1;
  BOOL hasName_:1;
  BOOL hasUnit_:1;
  BOOL hasCategory_:1;
  BOOL isFav_:1;
  Float64 num;
  Float64 price;
  int32_t id;
  NSString* name;
  NSString* unit;
  ProductCategory* category;
  PBAppendableArray * specificationsArray;
}
- (BOOL) hasId;
- (BOOL) hasName;
- (BOOL) hasNum;
- (BOOL) hasUnit;
- (BOOL) hasPrice;
- (BOOL) hasCategory;
- (BOOL) hasIsFav;
@property (readonly) int32_t id;
@property (readonly, retain) NSString* name;
@property (readonly) Float64 num;
@property (readonly, retain) NSString* unit;
@property (readonly) Float64 price;
@property (readonly, retain) ProductCategory* category;
- (BOOL) isFav;
@property (readonly, retain) PBArray * specifications;
- (ProductSpecification*)specificationsAtIndex:(NSUInteger)index;

+ (Product*) defaultInstance;
- (Product*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Product_Builder*) builder;
+ (Product_Builder*) builder;
+ (Product_Builder*) builderWithPrototype:(Product*) prototype;
- (Product_Builder*) toBuilder;

+ (Product*) parseFromData:(NSData*) data;
+ (Product*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Product*) parseFromInputStream:(NSInputStream*) input;
+ (Product*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Product*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Product*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Product_Builder : PBGeneratedMessage_Builder {
@private
  Product* result;
}

- (Product*) defaultInstance;

- (Product_Builder*) clear;
- (Product_Builder*) clone;

- (Product*) build;
- (Product*) buildPartial;

- (Product_Builder*) mergeFrom:(Product*) other;
- (Product_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Product_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (int32_t) id;
- (Product_Builder*) setId:(int32_t) value;
- (Product_Builder*) clearId;

- (BOOL) hasName;
- (NSString*) name;
- (Product_Builder*) setName:(NSString*) value;
- (Product_Builder*) clearName;

- (BOOL) hasNum;
- (Float64) num;
- (Product_Builder*) setNum:(Float64) value;
- (Product_Builder*) clearNum;

- (BOOL) hasUnit;
- (NSString*) unit;
- (Product_Builder*) setUnit:(NSString*) value;
- (Product_Builder*) clearUnit;

- (BOOL) hasPrice;
- (Float64) price;
- (Product_Builder*) setPrice:(Float64) value;
- (Product_Builder*) clearPrice;

- (BOOL) hasCategory;
- (ProductCategory*) category;
- (Product_Builder*) setCategory:(ProductCategory*) value;
- (Product_Builder*) setCategoryBuilder:(ProductCategory_Builder*) builderForValue;
- (Product_Builder*) mergeCategory:(ProductCategory*) value;
- (Product_Builder*) clearCategory;

- (BOOL) hasIsFav;
- (BOOL) isFav;
- (Product_Builder*) setIsFav:(BOOL) value;
- (Product_Builder*) clearIsFav;

- (PBAppendableArray *)specifications;
- (ProductSpecification*)specificationsAtIndex:(NSUInteger)index;
- (Product_Builder *)addSpecifications:(ProductSpecification*)value;
- (Product_Builder *)setSpecificationsArray:(NSArray *)array;
- (Product_Builder *)setSpecificationsValues:(const ProductSpecification* *)values count:(NSUInteger)count;
- (Product_Builder *)clearSpecifications;
@end

@interface ProductParams : PBGeneratedMessage {
@private
  BOOL hasPage_:1;
  BOOL hasName_:1;
  BOOL hasBarcode_:1;
  BOOL hasPriceSort_:1;
  int32_t page;
  NSString* name;
  NSString* barcode;
  PriceSort priceSort;
  PBAppendableArray * categoriesArray;
  PBAppendableArray * specificationValueArray;
}
- (BOOL) hasPage;
- (BOOL) hasName;
- (BOOL) hasBarcode;
- (BOOL) hasPriceSort;
@property (readonly) int32_t page;
@property (readonly, retain) NSString* name;
@property (readonly, retain) NSString* barcode;
@property (readonly) PriceSort priceSort;
@property (readonly, retain) PBArray * categories;
@property (readonly, retain) PBArray * specificationValue;
- (ProductCategory*)categoriesAtIndex:(NSUInteger)index;
- (ProductSpecificationValue*)specificationValueAtIndex:(NSUInteger)index;

+ (ProductParams*) defaultInstance;
- (ProductParams*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProductParams_Builder*) builder;
+ (ProductParams_Builder*) builder;
+ (ProductParams_Builder*) builderWithPrototype:(ProductParams*) prototype;
- (ProductParams_Builder*) toBuilder;

+ (ProductParams*) parseFromData:(NSData*) data;
+ (ProductParams*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProductParams*) parseFromInputStream:(NSInputStream*) input;
+ (ProductParams*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProductParams*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProductParams*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProductParams_Builder : PBGeneratedMessage_Builder {
@private
  ProductParams* result;
}

- (ProductParams*) defaultInstance;

- (ProductParams_Builder*) clear;
- (ProductParams_Builder*) clone;

- (ProductParams*) build;
- (ProductParams*) buildPartial;

- (ProductParams_Builder*) mergeFrom:(ProductParams*) other;
- (ProductParams_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProductParams_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPage;
- (int32_t) page;
- (ProductParams_Builder*) setPage:(int32_t) value;
- (ProductParams_Builder*) clearPage;

- (BOOL) hasName;
- (NSString*) name;
- (ProductParams_Builder*) setName:(NSString*) value;
- (ProductParams_Builder*) clearName;

- (BOOL) hasBarcode;
- (NSString*) barcode;
- (ProductParams_Builder*) setBarcode:(NSString*) value;
- (ProductParams_Builder*) clearBarcode;

- (BOOL) hasPriceSort;
- (PriceSort) priceSort;
- (ProductParams_Builder*) setPriceSort:(PriceSort) value;
- (ProductParams_Builder*) clearPriceSort;

- (PBAppendableArray *)categories;
- (ProductCategory*)categoriesAtIndex:(NSUInteger)index;
- (ProductParams_Builder *)addCategories:(ProductCategory*)value;
- (ProductParams_Builder *)setCategoriesArray:(NSArray *)array;
- (ProductParams_Builder *)setCategoriesValues:(const ProductCategory* *)values count:(NSUInteger)count;
- (ProductParams_Builder *)clearCategories;

- (PBAppendableArray *)specificationValue;
- (ProductSpecificationValue*)specificationValueAtIndex:(NSUInteger)index;
- (ProductParams_Builder *)addSpecificationValue:(ProductSpecificationValue*)value;
- (ProductParams_Builder *)setSpecificationValueArray:(NSArray *)array;
- (ProductParams_Builder *)setSpecificationValueValues:(const ProductSpecificationValue* *)values count:(NSUInteger)count;
- (ProductParams_Builder *)clearSpecificationValue;
@end

@interface ProductCategory : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasParentId_:1;
  BOOL hasName_:1;
  BOOL hasPath_:1;
  int32_t id;
  int32_t parentId;
  NSString* name;
  NSString* path;
}
- (BOOL) hasId;
- (BOOL) hasName;
- (BOOL) hasParentId;
- (BOOL) hasPath;
@property (readonly) int32_t id;
@property (readonly, retain) NSString* name;
@property (readonly) int32_t parentId;
@property (readonly, retain) NSString* path;

+ (ProductCategory*) defaultInstance;
- (ProductCategory*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProductCategory_Builder*) builder;
+ (ProductCategory_Builder*) builder;
+ (ProductCategory_Builder*) builderWithPrototype:(ProductCategory*) prototype;
- (ProductCategory_Builder*) toBuilder;

+ (ProductCategory*) parseFromData:(NSData*) data;
+ (ProductCategory*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProductCategory*) parseFromInputStream:(NSInputStream*) input;
+ (ProductCategory*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProductCategory*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProductCategory*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProductCategory_Builder : PBGeneratedMessage_Builder {
@private
  ProductCategory* result;
}

- (ProductCategory*) defaultInstance;

- (ProductCategory_Builder*) clear;
- (ProductCategory_Builder*) clone;

- (ProductCategory*) build;
- (ProductCategory*) buildPartial;

- (ProductCategory_Builder*) mergeFrom:(ProductCategory*) other;
- (ProductCategory_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProductCategory_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (int32_t) id;
- (ProductCategory_Builder*) setId:(int32_t) value;
- (ProductCategory_Builder*) clearId;

- (BOOL) hasName;
- (NSString*) name;
- (ProductCategory_Builder*) setName:(NSString*) value;
- (ProductCategory_Builder*) clearName;

- (BOOL) hasParentId;
- (int32_t) parentId;
- (ProductCategory_Builder*) setParentId:(int32_t) value;
- (ProductCategory_Builder*) clearParentId;

- (BOOL) hasPath;
- (NSString*) path;
- (ProductCategory_Builder*) setPath:(NSString*) value;
- (ProductCategory_Builder*) clearPath;
@end

@interface ProductSpecification : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasName_:1;
  int32_t id;
  NSString* name;
  PBAppendableArray * specificationValuesArray;
}
- (BOOL) hasId;
- (BOOL) hasName;
@property (readonly) int32_t id;
@property (readonly, retain) NSString* name;
@property (readonly, retain) PBArray * specificationValues;
- (ProductSpecificationValue*)specificationValuesAtIndex:(NSUInteger)index;

+ (ProductSpecification*) defaultInstance;
- (ProductSpecification*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProductSpecification_Builder*) builder;
+ (ProductSpecification_Builder*) builder;
+ (ProductSpecification_Builder*) builderWithPrototype:(ProductSpecification*) prototype;
- (ProductSpecification_Builder*) toBuilder;

+ (ProductSpecification*) parseFromData:(NSData*) data;
+ (ProductSpecification*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProductSpecification*) parseFromInputStream:(NSInputStream*) input;
+ (ProductSpecification*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProductSpecification*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProductSpecification*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProductSpecification_Builder : PBGeneratedMessage_Builder {
@private
  ProductSpecification* result;
}

- (ProductSpecification*) defaultInstance;

- (ProductSpecification_Builder*) clear;
- (ProductSpecification_Builder*) clone;

- (ProductSpecification*) build;
- (ProductSpecification*) buildPartial;

- (ProductSpecification_Builder*) mergeFrom:(ProductSpecification*) other;
- (ProductSpecification_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProductSpecification_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (int32_t) id;
- (ProductSpecification_Builder*) setId:(int32_t) value;
- (ProductSpecification_Builder*) clearId;

- (BOOL) hasName;
- (NSString*) name;
- (ProductSpecification_Builder*) setName:(NSString*) value;
- (ProductSpecification_Builder*) clearName;

- (PBAppendableArray *)specificationValues;
- (ProductSpecificationValue*)specificationValuesAtIndex:(NSUInteger)index;
- (ProductSpecification_Builder *)addSpecificationValues:(ProductSpecificationValue*)value;
- (ProductSpecification_Builder *)setSpecificationValuesArray:(NSArray *)array;
- (ProductSpecification_Builder *)setSpecificationValuesValues:(const ProductSpecificationValue* *)values count:(NSUInteger)count;
- (ProductSpecification_Builder *)clearSpecificationValues;
@end

@interface ProductSpecificationValue : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasName_:1;
  int32_t id;
  NSString* name;
}
- (BOOL) hasId;
- (BOOL) hasName;
@property (readonly) int32_t id;
@property (readonly, retain) NSString* name;

+ (ProductSpecificationValue*) defaultInstance;
- (ProductSpecificationValue*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProductSpecificationValue_Builder*) builder;
+ (ProductSpecificationValue_Builder*) builder;
+ (ProductSpecificationValue_Builder*) builderWithPrototype:(ProductSpecificationValue*) prototype;
- (ProductSpecificationValue_Builder*) toBuilder;

+ (ProductSpecificationValue*) parseFromData:(NSData*) data;
+ (ProductSpecificationValue*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProductSpecificationValue*) parseFromInputStream:(NSInputStream*) input;
+ (ProductSpecificationValue*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProductSpecificationValue*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProductSpecificationValue*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProductSpecificationValue_Builder : PBGeneratedMessage_Builder {
@private
  ProductSpecificationValue* result;
}

- (ProductSpecificationValue*) defaultInstance;

- (ProductSpecificationValue_Builder*) clear;
- (ProductSpecificationValue_Builder*) clone;

- (ProductSpecificationValue*) build;
- (ProductSpecificationValue*) buildPartial;

- (ProductSpecificationValue_Builder*) mergeFrom:(ProductSpecificationValue*) other;
- (ProductSpecificationValue_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProductSpecificationValue_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (int32_t) id;
- (ProductSpecificationValue_Builder*) setId:(int32_t) value;
- (ProductSpecificationValue_Builder*) clearId;

- (BOOL) hasName;
- (NSString*) name;
- (ProductSpecificationValue_Builder*) setName:(NSString*) value;
- (ProductSpecificationValue_Builder*) clearName;
@end

