// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Product.pb.h"

@implementation ProductRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [ProductRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

BOOL PriceSortIsValidValue(PriceSort value) {
  switch (value) {
    case PriceSortAsc:
    case PriceSortDes:
      return YES;
    default:
      return NO;
  }
}
@interface Product ()
@property int32_t id;
@property (retain) NSString* name;
@property Float64 num;
@property (retain) NSString* unit;
@property Float64 price;
@property (retain) ProductCategory* category;
@property BOOL isFav;
@property (retain) PBAppendableArray * specificationsArray;
@end

@implementation Product

- (BOOL) hasId {
  return !!hasId_;
}
- (void) setHasId:(BOOL) value_ {
  hasId_ = !!value_;
}
@synthesize id;
- (BOOL) hasName {
  return !!hasName_;
}
- (void) setHasName:(BOOL) value_ {
  hasName_ = !!value_;
}
@synthesize name;
- (BOOL) hasNum {
  return !!hasNum_;
}
- (void) setHasNum:(BOOL) value_ {
  hasNum_ = !!value_;
}
@synthesize num;
- (BOOL) hasUnit {
  return !!hasUnit_;
}
- (void) setHasUnit:(BOOL) value_ {
  hasUnit_ = !!value_;
}
@synthesize unit;
- (BOOL) hasPrice {
  return !!hasPrice_;
}
- (void) setHasPrice:(BOOL) value_ {
  hasPrice_ = !!value_;
}
@synthesize price;
- (BOOL) hasCategory {
  return !!hasCategory_;
}
- (void) setHasCategory:(BOOL) value_ {
  hasCategory_ = !!value_;
}
@synthesize category;
- (BOOL) hasIsFav {
  return !!hasIsFav_;
}
- (void) setHasIsFav:(BOOL) value_ {
  hasIsFav_ = !!value_;
}
- (BOOL) isFav {
  return !!isFav_;
}
- (void) setIsFav:(BOOL) value_ {
  isFav_ = !!value_;
}
@synthesize specificationsArray;
@dynamic specifications;
- (void) dealloc {
  self.name = nil;
  self.unit = nil;
  self.category = nil;
  self.specificationsArray = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.id = 0;
    self.name = @"";
    self.num = 0;
    self.unit = @"";
    self.price = 0;
    self.category = [ProductCategory defaultInstance];
    self.isFav = NO;
  }
  return self;
}
static Product* defaultProductInstance = nil;
+ (void) initialize {
  if (self == [Product class]) {
    defaultProductInstance = [[Product alloc] init];
  }
}
+ (Product*) defaultInstance {
  return defaultProductInstance;
}
- (Product*) defaultInstance {
  return defaultProductInstance;
}
- (PBArray *)specifications {
  return specificationsArray;
}
- (ProductSpecification*)specificationsAtIndex:(NSUInteger)index {
  return [specificationsArray objectAtIndex:index];
}
- (BOOL) isInitialized {
  if (!self.hasId) {
    return NO;
  }
  if (!self.hasName) {
    return NO;
  }
  if (self.hasCategory) {
    if (!self.category.isInitialized) {
      return NO;
    }
  }
  for (ProductSpecification* element in self.specifications) {
    if (!element.isInitialized) {
      return NO;
    }
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasId) {
    [output writeInt32:1 value:self.id];
  }
  if (self.hasName) {
    [output writeString:2 value:self.name];
  }
  if (self.hasNum) {
    [output writeDouble:3 value:self.num];
  }
  if (self.hasUnit) {
    [output writeString:4 value:self.unit];
  }
  if (self.hasPrice) {
    [output writeDouble:5 value:self.price];
  }
  if (self.hasCategory) {
    [output writeMessage:6 value:self.category];
  }
  if (self.hasIsFav) {
    [output writeBool:7 value:self.isFav];
  }
  for (ProductSpecification *element in self.specificationsArray) {
    [output writeMessage:8 value:element];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasId) {
    size_ += computeInt32Size(1, self.id);
  }
  if (self.hasName) {
    size_ += computeStringSize(2, self.name);
  }
  if (self.hasNum) {
    size_ += computeDoubleSize(3, self.num);
  }
  if (self.hasUnit) {
    size_ += computeStringSize(4, self.unit);
  }
  if (self.hasPrice) {
    size_ += computeDoubleSize(5, self.price);
  }
  if (self.hasCategory) {
    size_ += computeMessageSize(6, self.category);
  }
  if (self.hasIsFav) {
    size_ += computeBoolSize(7, self.isFav);
  }
  for (ProductSpecification *element in self.specificationsArray) {
    size_ += computeMessageSize(8, element);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (Product*) parseFromData:(NSData*) data {
  return (Product*)[[[Product builder] mergeFromData:data] build];
}
+ (Product*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Product*)[[[Product builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (Product*) parseFromInputStream:(NSInputStream*) input {
  return (Product*)[[[Product builder] mergeFromInputStream:input] build];
}
+ (Product*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Product*)[[[Product builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Product*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (Product*)[[[Product builder] mergeFromCodedInputStream:input] build];
}
+ (Product*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Product*)[[[Product builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Product_Builder*) builder {
  return [[[Product_Builder alloc] init] autorelease];
}
+ (Product_Builder*) builderWithPrototype:(Product*) prototype {
  return [[Product builder] mergeFrom:prototype];
}
- (Product_Builder*) builder {
  return [Product builder];
}
- (Product_Builder*) toBuilder {
  return [Product builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"id", [NSNumber numberWithInt:self.id]];
  }
  if (self.hasName) {
    [output appendFormat:@"%@%@: %@\n", indent, @"name", self.name];
  }
  if (self.hasNum) {
    [output appendFormat:@"%@%@: %@\n", indent, @"num", [NSNumber numberWithDouble:self.num]];
  }
  if (self.hasUnit) {
    [output appendFormat:@"%@%@: %@\n", indent, @"unit", self.unit];
  }
  if (self.hasPrice) {
    [output appendFormat:@"%@%@: %@\n", indent, @"price", [NSNumber numberWithDouble:self.price]];
  }
  if (self.hasCategory) {
    [output appendFormat:@"%@%@ {\n", indent, @"category"];
    [self.category writeDescriptionTo:output
                         withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }
  if (self.hasIsFav) {
    [output appendFormat:@"%@%@: %@\n", indent, @"isFav", [NSNumber numberWithBool:self.isFav]];
  }
  for (ProductSpecification* element in self.specificationsArray) {
    [output appendFormat:@"%@%@ {\n", indent, @"specifications"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[Product class]]) {
    return NO;
  }
  Product *otherMessage = other;
  return
      self.hasId == otherMessage.hasId &&
      (!self.hasId || self.id == otherMessage.id) &&
      self.hasName == otherMessage.hasName &&
      (!self.hasName || [self.name isEqual:otherMessage.name]) &&
      self.hasNum == otherMessage.hasNum &&
      (!self.hasNum || self.num == otherMessage.num) &&
      self.hasUnit == otherMessage.hasUnit &&
      (!self.hasUnit || [self.unit isEqual:otherMessage.unit]) &&
      self.hasPrice == otherMessage.hasPrice &&
      (!self.hasPrice || self.price == otherMessage.price) &&
      self.hasCategory == otherMessage.hasCategory &&
      (!self.hasCategory || [self.category isEqual:otherMessage.category]) &&
      self.hasIsFav == otherMessage.hasIsFav &&
      (!self.hasIsFav || self.isFav == otherMessage.isFav) &&
      [self.specificationsArray isEqualToArray:otherMessage.specificationsArray] &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  NSUInteger hashCode = 7;
  if (self.hasId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.id] hash];
  }
  if (self.hasName) {
    hashCode = hashCode * 31 + [self.name hash];
  }
  if (self.hasNum) {
    hashCode = hashCode * 31 + [[NSNumber numberWithDouble:self.num] hash];
  }
  if (self.hasUnit) {
    hashCode = hashCode * 31 + [self.unit hash];
  }
  if (self.hasPrice) {
    hashCode = hashCode * 31 + [[NSNumber numberWithDouble:self.price] hash];
  }
  if (self.hasCategory) {
    hashCode = hashCode * 31 + [self.category hash];
  }
  if (self.hasIsFav) {
    hashCode = hashCode * 31 + [[NSNumber numberWithBool:self.isFav] hash];
  }
  for (ProductSpecification* element in self.specificationsArray) {
    hashCode = hashCode * 31 + [element hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface Product_Builder()
@property (retain) Product* result;
@end

@implementation Product_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[Product alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (Product_Builder*) clear {
  self.result = [[[Product alloc] init] autorelease];
  return self;
}
- (Product_Builder*) clone {
  return [Product builderWithPrototype:result];
}
- (Product*) defaultInstance {
  return [Product defaultInstance];
}
- (Product*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (Product*) buildPartial {
  Product* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (Product_Builder*) mergeFrom:(Product*) other {
  if (other == [Product defaultInstance]) {
    return self;
  }
  if (other.hasId) {
    [self setId:other.id];
  }
  if (other.hasName) {
    [self setName:other.name];
  }
  if (other.hasNum) {
    [self setNum:other.num];
  }
  if (other.hasUnit) {
    [self setUnit:other.unit];
  }
  if (other.hasPrice) {
    [self setPrice:other.price];
  }
  if (other.hasCategory) {
    [self mergeCategory:other.category];
  }
  if (other.hasIsFav) {
    [self setIsFav:other.isFav];
  }
  if (other.specificationsArray.count > 0) {
    if (result.specificationsArray == nil) {
      result.specificationsArray = [[other.specificationsArray copyWithZone:[other.specificationsArray zone]] autorelease];
    } else {
      [result.specificationsArray appendArray:other.specificationsArray];
    }
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (Product_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (Product_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setId:[input readInt32]];
        break;
      }
      case 18: {
        [self setName:[input readString]];
        break;
      }
      case 25: {
        [self setNum:[input readDouble]];
        break;
      }
      case 34: {
        [self setUnit:[input readString]];
        break;
      }
      case 41: {
        [self setPrice:[input readDouble]];
        break;
      }
      case 50: {
        ProductCategory_Builder* subBuilder = [ProductCategory builder];
        if (self.hasCategory) {
          [subBuilder mergeFrom:self.category];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setCategory:[subBuilder buildPartial]];
        break;
      }
      case 56: {
        [self setIsFav:[input readBool]];
        break;
      }
      case 66: {
        ProductSpecification_Builder* subBuilder = [ProductSpecification builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addSpecifications:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (BOOL) hasId {
  return result.hasId;
}
- (int32_t) id {
  return result.id;
}
- (Product_Builder*) setId:(int32_t) value {
  result.hasId = YES;
  result.id = value;
  return self;
}
- (Product_Builder*) clearId {
  result.hasId = NO;
  result.id = 0;
  return self;
}
- (BOOL) hasName {
  return result.hasName;
}
- (NSString*) name {
  return result.name;
}
- (Product_Builder*) setName:(NSString*) value {
  result.hasName = YES;
  result.name = value;
  return self;
}
- (Product_Builder*) clearName {
  result.hasName = NO;
  result.name = @"";
  return self;
}
- (BOOL) hasNum {
  return result.hasNum;
}
- (Float64) num {
  return result.num;
}
- (Product_Builder*) setNum:(Float64) value {
  result.hasNum = YES;
  result.num = value;
  return self;
}
- (Product_Builder*) clearNum {
  result.hasNum = NO;
  result.num = 0;
  return self;
}
- (BOOL) hasUnit {
  return result.hasUnit;
}
- (NSString*) unit {
  return result.unit;
}
- (Product_Builder*) setUnit:(NSString*) value {
  result.hasUnit = YES;
  result.unit = value;
  return self;
}
- (Product_Builder*) clearUnit {
  result.hasUnit = NO;
  result.unit = @"";
  return self;
}
- (BOOL) hasPrice {
  return result.hasPrice;
}
- (Float64) price {
  return result.price;
}
- (Product_Builder*) setPrice:(Float64) value {
  result.hasPrice = YES;
  result.price = value;
  return self;
}
- (Product_Builder*) clearPrice {
  result.hasPrice = NO;
  result.price = 0;
  return self;
}
- (BOOL) hasCategory {
  return result.hasCategory;
}
- (ProductCategory*) category {
  return result.category;
}
- (Product_Builder*) setCategory:(ProductCategory*) value {
  result.hasCategory = YES;
  result.category = value;
  return self;
}
- (Product_Builder*) setCategoryBuilder:(ProductCategory_Builder*) builderForValue {
  return [self setCategory:[builderForValue build]];
}
- (Product_Builder*) mergeCategory:(ProductCategory*) value {
  if (result.hasCategory &&
      result.category != [ProductCategory defaultInstance]) {
    result.category =
      [[[ProductCategory builderWithPrototype:result.category] mergeFrom:value] buildPartial];
  } else {
    result.category = value;
  }
  result.hasCategory = YES;
  return self;
}
- (Product_Builder*) clearCategory {
  result.hasCategory = NO;
  result.category = [ProductCategory defaultInstance];
  return self;
}
- (BOOL) hasIsFav {
  return result.hasIsFav;
}
- (BOOL) isFav {
  return result.isFav;
}
- (Product_Builder*) setIsFav:(BOOL) value {
  result.hasIsFav = YES;
  result.isFav = value;
  return self;
}
- (Product_Builder*) clearIsFav {
  result.hasIsFav = NO;
  result.isFav = NO;
  return self;
}
- (PBAppendableArray *)specifications {
  return result.specificationsArray;
}
- (ProductSpecification*)specificationsAtIndex:(NSUInteger)index {
  return [result specificationsAtIndex:index];
}
- (Product_Builder *)addSpecifications:(ProductSpecification*)value {
  if (result.specificationsArray == nil) {
    result.specificationsArray = [PBAppendableArray arrayWithValueType:PBArrayValueTypeObject];
  }
  [result.specificationsArray addObject:value];
  return self;
}
- (Product_Builder *)setSpecificationsArray:(NSArray *)array {
  result.specificationsArray = [PBAppendableArray arrayWithArray:array valueType:PBArrayValueTypeObject];
  return self;
}
- (Product_Builder *)setSpecificationsValues:(const ProductSpecification* *)values count:(NSUInteger)count {
  result.specificationsArray = [PBAppendableArray arrayWithValues:values count:count valueType:PBArrayValueTypeObject];
  return self;
}
- (Product_Builder *)clearSpecifications {
  result.specificationsArray = nil;
  return self;
}
@end

@interface ProductParams ()
@property int32_t page;
@property (retain) NSString* name;
@property (retain) NSString* barcode;
@property PriceSort priceSort;
@property (retain) PBAppendableArray * categoriesArray;
@property (retain) PBAppendableArray * specificationValueArray;
@end

@implementation ProductParams

- (BOOL) hasPage {
  return !!hasPage_;
}
- (void) setHasPage:(BOOL) value_ {
  hasPage_ = !!value_;
}
@synthesize page;
- (BOOL) hasName {
  return !!hasName_;
}
- (void) setHasName:(BOOL) value_ {
  hasName_ = !!value_;
}
@synthesize name;
- (BOOL) hasBarcode {
  return !!hasBarcode_;
}
- (void) setHasBarcode:(BOOL) value_ {
  hasBarcode_ = !!value_;
}
@synthesize barcode;
- (BOOL) hasPriceSort {
  return !!hasPriceSort_;
}
- (void) setHasPriceSort:(BOOL) value_ {
  hasPriceSort_ = !!value_;
}
@synthesize priceSort;
@synthesize categoriesArray;
@dynamic categories;
@synthesize specificationValueArray;
@dynamic specificationValue;
- (void) dealloc {
  self.name = nil;
  self.barcode = nil;
  self.categoriesArray = nil;
  self.specificationValueArray = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.page = 0;
    self.name = @"";
    self.barcode = @"";
    self.priceSort = PriceSortAsc;
  }
  return self;
}
static ProductParams* defaultProductParamsInstance = nil;
+ (void) initialize {
  if (self == [ProductParams class]) {
    defaultProductParamsInstance = [[ProductParams alloc] init];
  }
}
+ (ProductParams*) defaultInstance {
  return defaultProductParamsInstance;
}
- (ProductParams*) defaultInstance {
  return defaultProductParamsInstance;
}
- (PBArray *)categories {
  return categoriesArray;
}
- (ProductCategory*)categoriesAtIndex:(NSUInteger)index {
  return [categoriesArray objectAtIndex:index];
}
- (PBArray *)specificationValue {
  return specificationValueArray;
}
- (ProductSpecificationValue*)specificationValueAtIndex:(NSUInteger)index {
  return [specificationValueArray objectAtIndex:index];
}
- (BOOL) isInitialized {
  for (ProductCategory* element in self.categories) {
    if (!element.isInitialized) {
      return NO;
    }
  }
  for (ProductSpecificationValue* element in self.specificationValue) {
    if (!element.isInitialized) {
      return NO;
    }
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasPage) {
    [output writeInt32:1 value:self.page];
  }
  if (self.hasName) {
    [output writeString:2 value:self.name];
  }
  if (self.hasBarcode) {
    [output writeString:3 value:self.barcode];
  }
  if (self.hasPriceSort) {
    [output writeEnum:4 value:self.priceSort];
  }
  for (ProductCategory *element in self.categoriesArray) {
    [output writeMessage:5 value:element];
  }
  for (ProductSpecificationValue *element in self.specificationValueArray) {
    [output writeMessage:6 value:element];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasPage) {
    size_ += computeInt32Size(1, self.page);
  }
  if (self.hasName) {
    size_ += computeStringSize(2, self.name);
  }
  if (self.hasBarcode) {
    size_ += computeStringSize(3, self.barcode);
  }
  if (self.hasPriceSort) {
    size_ += computeEnumSize(4, self.priceSort);
  }
  for (ProductCategory *element in self.categoriesArray) {
    size_ += computeMessageSize(5, element);
  }
  for (ProductSpecificationValue *element in self.specificationValueArray) {
    size_ += computeMessageSize(6, element);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (ProductParams*) parseFromData:(NSData*) data {
  return (ProductParams*)[[[ProductParams builder] mergeFromData:data] build];
}
+ (ProductParams*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ProductParams*)[[[ProductParams builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (ProductParams*) parseFromInputStream:(NSInputStream*) input {
  return (ProductParams*)[[[ProductParams builder] mergeFromInputStream:input] build];
}
+ (ProductParams*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ProductParams*)[[[ProductParams builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ProductParams*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (ProductParams*)[[[ProductParams builder] mergeFromCodedInputStream:input] build];
}
+ (ProductParams*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ProductParams*)[[[ProductParams builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ProductParams_Builder*) builder {
  return [[[ProductParams_Builder alloc] init] autorelease];
}
+ (ProductParams_Builder*) builderWithPrototype:(ProductParams*) prototype {
  return [[ProductParams builder] mergeFrom:prototype];
}
- (ProductParams_Builder*) builder {
  return [ProductParams builder];
}
- (ProductParams_Builder*) toBuilder {
  return [ProductParams builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasPage) {
    [output appendFormat:@"%@%@: %@\n", indent, @"page", [NSNumber numberWithInt:self.page]];
  }
  if (self.hasName) {
    [output appendFormat:@"%@%@: %@\n", indent, @"name", self.name];
  }
  if (self.hasBarcode) {
    [output appendFormat:@"%@%@: %@\n", indent, @"barcode", self.barcode];
  }
  if (self.hasPriceSort) {
    [output appendFormat:@"%@%@: %d\n", indent, @"priceSort", self.priceSort];
  }
  for (ProductCategory* element in self.categoriesArray) {
    [output appendFormat:@"%@%@ {\n", indent, @"categories"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }
  for (ProductSpecificationValue* element in self.specificationValueArray) {
    [output appendFormat:@"%@%@ {\n", indent, @"specificationValue"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[ProductParams class]]) {
    return NO;
  }
  ProductParams *otherMessage = other;
  return
      self.hasPage == otherMessage.hasPage &&
      (!self.hasPage || self.page == otherMessage.page) &&
      self.hasName == otherMessage.hasName &&
      (!self.hasName || [self.name isEqual:otherMessage.name]) &&
      self.hasBarcode == otherMessage.hasBarcode &&
      (!self.hasBarcode || [self.barcode isEqual:otherMessage.barcode]) &&
      self.hasPriceSort == otherMessage.hasPriceSort &&
      (!self.hasPriceSort || self.priceSort == otherMessage.priceSort) &&
      [self.categoriesArray isEqualToArray:otherMessage.categoriesArray] &&
      [self.specificationValueArray isEqualToArray:otherMessage.specificationValueArray] &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  NSUInteger hashCode = 7;
  if (self.hasPage) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.page] hash];
  }
  if (self.hasName) {
    hashCode = hashCode * 31 + [self.name hash];
  }
  if (self.hasBarcode) {
    hashCode = hashCode * 31 + [self.barcode hash];
  }
  if (self.hasPriceSort) {
    hashCode = hashCode * 31 + self.priceSort;
  }
  for (ProductCategory* element in self.categoriesArray) {
    hashCode = hashCode * 31 + [element hash];
  }
  for (ProductSpecificationValue* element in self.specificationValueArray) {
    hashCode = hashCode * 31 + [element hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface ProductParams_Builder()
@property (retain) ProductParams* result;
@end

@implementation ProductParams_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[ProductParams alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (ProductParams_Builder*) clear {
  self.result = [[[ProductParams alloc] init] autorelease];
  return self;
}
- (ProductParams_Builder*) clone {
  return [ProductParams builderWithPrototype:result];
}
- (ProductParams*) defaultInstance {
  return [ProductParams defaultInstance];
}
- (ProductParams*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (ProductParams*) buildPartial {
  ProductParams* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (ProductParams_Builder*) mergeFrom:(ProductParams*) other {
  if (other == [ProductParams defaultInstance]) {
    return self;
  }
  if (other.hasPage) {
    [self setPage:other.page];
  }
  if (other.hasName) {
    [self setName:other.name];
  }
  if (other.hasBarcode) {
    [self setBarcode:other.barcode];
  }
  if (other.hasPriceSort) {
    [self setPriceSort:other.priceSort];
  }
  if (other.categoriesArray.count > 0) {
    if (result.categoriesArray == nil) {
      result.categoriesArray = [[other.categoriesArray copyWithZone:[other.categoriesArray zone]] autorelease];
    } else {
      [result.categoriesArray appendArray:other.categoriesArray];
    }
  }
  if (other.specificationValueArray.count > 0) {
    if (result.specificationValueArray == nil) {
      result.specificationValueArray = [[other.specificationValueArray copyWithZone:[other.specificationValueArray zone]] autorelease];
    } else {
      [result.specificationValueArray appendArray:other.specificationValueArray];
    }
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (ProductParams_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (ProductParams_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setPage:[input readInt32]];
        break;
      }
      case 18: {
        [self setName:[input readString]];
        break;
      }
      case 26: {
        [self setBarcode:[input readString]];
        break;
      }
      case 32: {
        int32_t value = [input readEnum];
        if (PriceSortIsValidValue(value)) {
          [self setPriceSort:value];
        } else {
          [unknownFields mergeVarintField:4 value:value];
        }
        break;
      }
      case 42: {
        ProductCategory_Builder* subBuilder = [ProductCategory builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addCategories:[subBuilder buildPartial]];
        break;
      }
      case 50: {
        ProductSpecificationValue_Builder* subBuilder = [ProductSpecificationValue builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addSpecificationValue:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (BOOL) hasPage {
  return result.hasPage;
}
- (int32_t) page {
  return result.page;
}
- (ProductParams_Builder*) setPage:(int32_t) value {
  result.hasPage = YES;
  result.page = value;
  return self;
}
- (ProductParams_Builder*) clearPage {
  result.hasPage = NO;
  result.page = 0;
  return self;
}
- (BOOL) hasName {
  return result.hasName;
}
- (NSString*) name {
  return result.name;
}
- (ProductParams_Builder*) setName:(NSString*) value {
  result.hasName = YES;
  result.name = value;
  return self;
}
- (ProductParams_Builder*) clearName {
  result.hasName = NO;
  result.name = @"";
  return self;
}
- (BOOL) hasBarcode {
  return result.hasBarcode;
}
- (NSString*) barcode {
  return result.barcode;
}
- (ProductParams_Builder*) setBarcode:(NSString*) value {
  result.hasBarcode = YES;
  result.barcode = value;
  return self;
}
- (ProductParams_Builder*) clearBarcode {
  result.hasBarcode = NO;
  result.barcode = @"";
  return self;
}
- (BOOL) hasPriceSort {
  return result.hasPriceSort;
}
- (PriceSort) priceSort {
  return result.priceSort;
}
- (ProductParams_Builder*) setPriceSort:(PriceSort) value {
  result.hasPriceSort = YES;
  result.priceSort = value;
  return self;
}
- (ProductParams_Builder*) clearPriceSort {
  result.hasPriceSort = NO;
  result.priceSort = PriceSortAsc;
  return self;
}
- (PBAppendableArray *)categories {
  return result.categoriesArray;
}
- (ProductCategory*)categoriesAtIndex:(NSUInteger)index {
  return [result categoriesAtIndex:index];
}
- (ProductParams_Builder *)addCategories:(ProductCategory*)value {
  if (result.categoriesArray == nil) {
    result.categoriesArray = [PBAppendableArray arrayWithValueType:PBArrayValueTypeObject];
  }
  [result.categoriesArray addObject:value];
  return self;
}
- (ProductParams_Builder *)setCategoriesArray:(NSArray *)array {
  result.categoriesArray = [PBAppendableArray arrayWithArray:array valueType:PBArrayValueTypeObject];
  return self;
}
- (ProductParams_Builder *)setCategoriesValues:(const ProductCategory* *)values count:(NSUInteger)count {
  result.categoriesArray = [PBAppendableArray arrayWithValues:values count:count valueType:PBArrayValueTypeObject];
  return self;
}
- (ProductParams_Builder *)clearCategories {
  result.categoriesArray = nil;
  return self;
}
- (PBAppendableArray *)specificationValue {
  return result.specificationValueArray;
}
- (ProductSpecificationValue*)specificationValueAtIndex:(NSUInteger)index {
  return [result specificationValueAtIndex:index];
}
- (ProductParams_Builder *)addSpecificationValue:(ProductSpecificationValue*)value {
  if (result.specificationValueArray == nil) {
    result.specificationValueArray = [PBAppendableArray arrayWithValueType:PBArrayValueTypeObject];
  }
  [result.specificationValueArray addObject:value];
  return self;
}
- (ProductParams_Builder *)setSpecificationValueArray:(NSArray *)array {
  result.specificationValueArray = [PBAppendableArray arrayWithArray:array valueType:PBArrayValueTypeObject];
  return self;
}
- (ProductParams_Builder *)setSpecificationValueValues:(const ProductSpecificationValue* *)values count:(NSUInteger)count {
  result.specificationValueArray = [PBAppendableArray arrayWithValues:values count:count valueType:PBArrayValueTypeObject];
  return self;
}
- (ProductParams_Builder *)clearSpecificationValue {
  result.specificationValueArray = nil;
  return self;
}
@end

@interface ProductCategory ()
@property int32_t id;
@property (retain) NSString* name;
@property int32_t parentId;
@property (retain) NSString* path;
@end

@implementation ProductCategory

- (BOOL) hasId {
  return !!hasId_;
}
- (void) setHasId:(BOOL) value_ {
  hasId_ = !!value_;
}
@synthesize id;
- (BOOL) hasName {
  return !!hasName_;
}
- (void) setHasName:(BOOL) value_ {
  hasName_ = !!value_;
}
@synthesize name;
- (BOOL) hasParentId {
  return !!hasParentId_;
}
- (void) setHasParentId:(BOOL) value_ {
  hasParentId_ = !!value_;
}
@synthesize parentId;
- (BOOL) hasPath {
  return !!hasPath_;
}
- (void) setHasPath:(BOOL) value_ {
  hasPath_ = !!value_;
}
@synthesize path;
- (void) dealloc {
  self.name = nil;
  self.path = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.id = 0;
    self.name = @"";
    self.parentId = 0;
    self.path = @"";
  }
  return self;
}
static ProductCategory* defaultProductCategoryInstance = nil;
+ (void) initialize {
  if (self == [ProductCategory class]) {
    defaultProductCategoryInstance = [[ProductCategory alloc] init];
  }
}
+ (ProductCategory*) defaultInstance {
  return defaultProductCategoryInstance;
}
- (ProductCategory*) defaultInstance {
  return defaultProductCategoryInstance;
}
- (BOOL) isInitialized {
  if (!self.hasId) {
    return NO;
  }
  if (!self.hasName) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasId) {
    [output writeInt32:1 value:self.id];
  }
  if (self.hasName) {
    [output writeString:2 value:self.name];
  }
  if (self.hasParentId) {
    [output writeInt32:3 value:self.parentId];
  }
  if (self.hasPath) {
    [output writeString:4 value:self.path];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasId) {
    size_ += computeInt32Size(1, self.id);
  }
  if (self.hasName) {
    size_ += computeStringSize(2, self.name);
  }
  if (self.hasParentId) {
    size_ += computeInt32Size(3, self.parentId);
  }
  if (self.hasPath) {
    size_ += computeStringSize(4, self.path);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (ProductCategory*) parseFromData:(NSData*) data {
  return (ProductCategory*)[[[ProductCategory builder] mergeFromData:data] build];
}
+ (ProductCategory*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ProductCategory*)[[[ProductCategory builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (ProductCategory*) parseFromInputStream:(NSInputStream*) input {
  return (ProductCategory*)[[[ProductCategory builder] mergeFromInputStream:input] build];
}
+ (ProductCategory*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ProductCategory*)[[[ProductCategory builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ProductCategory*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (ProductCategory*)[[[ProductCategory builder] mergeFromCodedInputStream:input] build];
}
+ (ProductCategory*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ProductCategory*)[[[ProductCategory builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ProductCategory_Builder*) builder {
  return [[[ProductCategory_Builder alloc] init] autorelease];
}
+ (ProductCategory_Builder*) builderWithPrototype:(ProductCategory*) prototype {
  return [[ProductCategory builder] mergeFrom:prototype];
}
- (ProductCategory_Builder*) builder {
  return [ProductCategory builder];
}
- (ProductCategory_Builder*) toBuilder {
  return [ProductCategory builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"id", [NSNumber numberWithInt:self.id]];
  }
  if (self.hasName) {
    [output appendFormat:@"%@%@: %@\n", indent, @"name", self.name];
  }
  if (self.hasParentId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"parentId", [NSNumber numberWithInt:self.parentId]];
  }
  if (self.hasPath) {
    [output appendFormat:@"%@%@: %@\n", indent, @"path", self.path];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[ProductCategory class]]) {
    return NO;
  }
  ProductCategory *otherMessage = other;
  return
      self.hasId == otherMessage.hasId &&
      (!self.hasId || self.id == otherMessage.id) &&
      self.hasName == otherMessage.hasName &&
      (!self.hasName || [self.name isEqual:otherMessage.name]) &&
      self.hasParentId == otherMessage.hasParentId &&
      (!self.hasParentId || self.parentId == otherMessage.parentId) &&
      self.hasPath == otherMessage.hasPath &&
      (!self.hasPath || [self.path isEqual:otherMessage.path]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  NSUInteger hashCode = 7;
  if (self.hasId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.id] hash];
  }
  if (self.hasName) {
    hashCode = hashCode * 31 + [self.name hash];
  }
  if (self.hasParentId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.parentId] hash];
  }
  if (self.hasPath) {
    hashCode = hashCode * 31 + [self.path hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface ProductCategory_Builder()
@property (retain) ProductCategory* result;
@end

@implementation ProductCategory_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[ProductCategory alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (ProductCategory_Builder*) clear {
  self.result = [[[ProductCategory alloc] init] autorelease];
  return self;
}
- (ProductCategory_Builder*) clone {
  return [ProductCategory builderWithPrototype:result];
}
- (ProductCategory*) defaultInstance {
  return [ProductCategory defaultInstance];
}
- (ProductCategory*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (ProductCategory*) buildPartial {
  ProductCategory* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (ProductCategory_Builder*) mergeFrom:(ProductCategory*) other {
  if (other == [ProductCategory defaultInstance]) {
    return self;
  }
  if (other.hasId) {
    [self setId:other.id];
  }
  if (other.hasName) {
    [self setName:other.name];
  }
  if (other.hasParentId) {
    [self setParentId:other.parentId];
  }
  if (other.hasPath) {
    [self setPath:other.path];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (ProductCategory_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (ProductCategory_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setId:[input readInt32]];
        break;
      }
      case 18: {
        [self setName:[input readString]];
        break;
      }
      case 24: {
        [self setParentId:[input readInt32]];
        break;
      }
      case 34: {
        [self setPath:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasId {
  return result.hasId;
}
- (int32_t) id {
  return result.id;
}
- (ProductCategory_Builder*) setId:(int32_t) value {
  result.hasId = YES;
  result.id = value;
  return self;
}
- (ProductCategory_Builder*) clearId {
  result.hasId = NO;
  result.id = 0;
  return self;
}
- (BOOL) hasName {
  return result.hasName;
}
- (NSString*) name {
  return result.name;
}
- (ProductCategory_Builder*) setName:(NSString*) value {
  result.hasName = YES;
  result.name = value;
  return self;
}
- (ProductCategory_Builder*) clearName {
  result.hasName = NO;
  result.name = @"";
  return self;
}
- (BOOL) hasParentId {
  return result.hasParentId;
}
- (int32_t) parentId {
  return result.parentId;
}
- (ProductCategory_Builder*) setParentId:(int32_t) value {
  result.hasParentId = YES;
  result.parentId = value;
  return self;
}
- (ProductCategory_Builder*) clearParentId {
  result.hasParentId = NO;
  result.parentId = 0;
  return self;
}
- (BOOL) hasPath {
  return result.hasPath;
}
- (NSString*) path {
  return result.path;
}
- (ProductCategory_Builder*) setPath:(NSString*) value {
  result.hasPath = YES;
  result.path = value;
  return self;
}
- (ProductCategory_Builder*) clearPath {
  result.hasPath = NO;
  result.path = @"";
  return self;
}
@end

@interface ProductSpecification ()
@property int32_t id;
@property (retain) NSString* name;
@property (retain) PBAppendableArray * specificationValuesArray;
@end

@implementation ProductSpecification

- (BOOL) hasId {
  return !!hasId_;
}
- (void) setHasId:(BOOL) value_ {
  hasId_ = !!value_;
}
@synthesize id;
- (BOOL) hasName {
  return !!hasName_;
}
- (void) setHasName:(BOOL) value_ {
  hasName_ = !!value_;
}
@synthesize name;
@synthesize specificationValuesArray;
@dynamic specificationValues;
- (void) dealloc {
  self.name = nil;
  self.specificationValuesArray = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.id = 0;
    self.name = @"";
  }
  return self;
}
static ProductSpecification* defaultProductSpecificationInstance = nil;
+ (void) initialize {
  if (self == [ProductSpecification class]) {
    defaultProductSpecificationInstance = [[ProductSpecification alloc] init];
  }
}
+ (ProductSpecification*) defaultInstance {
  return defaultProductSpecificationInstance;
}
- (ProductSpecification*) defaultInstance {
  return defaultProductSpecificationInstance;
}
- (PBArray *)specificationValues {
  return specificationValuesArray;
}
- (ProductSpecificationValue*)specificationValuesAtIndex:(NSUInteger)index {
  return [specificationValuesArray objectAtIndex:index];
}
- (BOOL) isInitialized {
  if (!self.hasId) {
    return NO;
  }
  if (!self.hasName) {
    return NO;
  }
  for (ProductSpecificationValue* element in self.specificationValues) {
    if (!element.isInitialized) {
      return NO;
    }
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasId) {
    [output writeInt32:1 value:self.id];
  }
  if (self.hasName) {
    [output writeString:2 value:self.name];
  }
  for (ProductSpecificationValue *element in self.specificationValuesArray) {
    [output writeMessage:3 value:element];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasId) {
    size_ += computeInt32Size(1, self.id);
  }
  if (self.hasName) {
    size_ += computeStringSize(2, self.name);
  }
  for (ProductSpecificationValue *element in self.specificationValuesArray) {
    size_ += computeMessageSize(3, element);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (ProductSpecification*) parseFromData:(NSData*) data {
  return (ProductSpecification*)[[[ProductSpecification builder] mergeFromData:data] build];
}
+ (ProductSpecification*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ProductSpecification*)[[[ProductSpecification builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (ProductSpecification*) parseFromInputStream:(NSInputStream*) input {
  return (ProductSpecification*)[[[ProductSpecification builder] mergeFromInputStream:input] build];
}
+ (ProductSpecification*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ProductSpecification*)[[[ProductSpecification builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ProductSpecification*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (ProductSpecification*)[[[ProductSpecification builder] mergeFromCodedInputStream:input] build];
}
+ (ProductSpecification*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ProductSpecification*)[[[ProductSpecification builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ProductSpecification_Builder*) builder {
  return [[[ProductSpecification_Builder alloc] init] autorelease];
}
+ (ProductSpecification_Builder*) builderWithPrototype:(ProductSpecification*) prototype {
  return [[ProductSpecification builder] mergeFrom:prototype];
}
- (ProductSpecification_Builder*) builder {
  return [ProductSpecification builder];
}
- (ProductSpecification_Builder*) toBuilder {
  return [ProductSpecification builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"id", [NSNumber numberWithInt:self.id]];
  }
  if (self.hasName) {
    [output appendFormat:@"%@%@: %@\n", indent, @"name", self.name];
  }
  for (ProductSpecificationValue* element in self.specificationValuesArray) {
    [output appendFormat:@"%@%@ {\n", indent, @"specificationValues"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[ProductSpecification class]]) {
    return NO;
  }
  ProductSpecification *otherMessage = other;
  return
      self.hasId == otherMessage.hasId &&
      (!self.hasId || self.id == otherMessage.id) &&
      self.hasName == otherMessage.hasName &&
      (!self.hasName || [self.name isEqual:otherMessage.name]) &&
      [self.specificationValuesArray isEqualToArray:otherMessage.specificationValuesArray] &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  NSUInteger hashCode = 7;
  if (self.hasId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.id] hash];
  }
  if (self.hasName) {
    hashCode = hashCode * 31 + [self.name hash];
  }
  for (ProductSpecificationValue* element in self.specificationValuesArray) {
    hashCode = hashCode * 31 + [element hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface ProductSpecification_Builder()
@property (retain) ProductSpecification* result;
@end

@implementation ProductSpecification_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[ProductSpecification alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (ProductSpecification_Builder*) clear {
  self.result = [[[ProductSpecification alloc] init] autorelease];
  return self;
}
- (ProductSpecification_Builder*) clone {
  return [ProductSpecification builderWithPrototype:result];
}
- (ProductSpecification*) defaultInstance {
  return [ProductSpecification defaultInstance];
}
- (ProductSpecification*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (ProductSpecification*) buildPartial {
  ProductSpecification* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (ProductSpecification_Builder*) mergeFrom:(ProductSpecification*) other {
  if (other == [ProductSpecification defaultInstance]) {
    return self;
  }
  if (other.hasId) {
    [self setId:other.id];
  }
  if (other.hasName) {
    [self setName:other.name];
  }
  if (other.specificationValuesArray.count > 0) {
    if (result.specificationValuesArray == nil) {
      result.specificationValuesArray = [[other.specificationValuesArray copyWithZone:[other.specificationValuesArray zone]] autorelease];
    } else {
      [result.specificationValuesArray appendArray:other.specificationValuesArray];
    }
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (ProductSpecification_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (ProductSpecification_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setId:[input readInt32]];
        break;
      }
      case 18: {
        [self setName:[input readString]];
        break;
      }
      case 26: {
        ProductSpecificationValue_Builder* subBuilder = [ProductSpecificationValue builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addSpecificationValues:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (BOOL) hasId {
  return result.hasId;
}
- (int32_t) id {
  return result.id;
}
- (ProductSpecification_Builder*) setId:(int32_t) value {
  result.hasId = YES;
  result.id = value;
  return self;
}
- (ProductSpecification_Builder*) clearId {
  result.hasId = NO;
  result.id = 0;
  return self;
}
- (BOOL) hasName {
  return result.hasName;
}
- (NSString*) name {
  return result.name;
}
- (ProductSpecification_Builder*) setName:(NSString*) value {
  result.hasName = YES;
  result.name = value;
  return self;
}
- (ProductSpecification_Builder*) clearName {
  result.hasName = NO;
  result.name = @"";
  return self;
}
- (PBAppendableArray *)specificationValues {
  return result.specificationValuesArray;
}
- (ProductSpecificationValue*)specificationValuesAtIndex:(NSUInteger)index {
  return [result specificationValuesAtIndex:index];
}
- (ProductSpecification_Builder *)addSpecificationValues:(ProductSpecificationValue*)value {
  if (result.specificationValuesArray == nil) {
    result.specificationValuesArray = [PBAppendableArray arrayWithValueType:PBArrayValueTypeObject];
  }
  [result.specificationValuesArray addObject:value];
  return self;
}
- (ProductSpecification_Builder *)setSpecificationValuesArray:(NSArray *)array {
  result.specificationValuesArray = [PBAppendableArray arrayWithArray:array valueType:PBArrayValueTypeObject];
  return self;
}
- (ProductSpecification_Builder *)setSpecificationValuesValues:(const ProductSpecificationValue* *)values count:(NSUInteger)count {
  result.specificationValuesArray = [PBAppendableArray arrayWithValues:values count:count valueType:PBArrayValueTypeObject];
  return self;
}
- (ProductSpecification_Builder *)clearSpecificationValues {
  result.specificationValuesArray = nil;
  return self;
}
@end

@interface ProductSpecificationValue ()
@property int32_t id;
@property (retain) NSString* name;
@end

@implementation ProductSpecificationValue

- (BOOL) hasId {
  return !!hasId_;
}
- (void) setHasId:(BOOL) value_ {
  hasId_ = !!value_;
}
@synthesize id;
- (BOOL) hasName {
  return !!hasName_;
}
- (void) setHasName:(BOOL) value_ {
  hasName_ = !!value_;
}
@synthesize name;
- (void) dealloc {
  self.name = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.id = 0;
    self.name = @"";
  }
  return self;
}
static ProductSpecificationValue* defaultProductSpecificationValueInstance = nil;
+ (void) initialize {
  if (self == [ProductSpecificationValue class]) {
    defaultProductSpecificationValueInstance = [[ProductSpecificationValue alloc] init];
  }
}
+ (ProductSpecificationValue*) defaultInstance {
  return defaultProductSpecificationValueInstance;
}
- (ProductSpecificationValue*) defaultInstance {
  return defaultProductSpecificationValueInstance;
}
- (BOOL) isInitialized {
  if (!self.hasId) {
    return NO;
  }
  if (!self.hasName) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasId) {
    [output writeInt32:1 value:self.id];
  }
  if (self.hasName) {
    [output writeString:2 value:self.name];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasId) {
    size_ += computeInt32Size(1, self.id);
  }
  if (self.hasName) {
    size_ += computeStringSize(2, self.name);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (ProductSpecificationValue*) parseFromData:(NSData*) data {
  return (ProductSpecificationValue*)[[[ProductSpecificationValue builder] mergeFromData:data] build];
}
+ (ProductSpecificationValue*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ProductSpecificationValue*)[[[ProductSpecificationValue builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (ProductSpecificationValue*) parseFromInputStream:(NSInputStream*) input {
  return (ProductSpecificationValue*)[[[ProductSpecificationValue builder] mergeFromInputStream:input] build];
}
+ (ProductSpecificationValue*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ProductSpecificationValue*)[[[ProductSpecificationValue builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ProductSpecificationValue*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (ProductSpecificationValue*)[[[ProductSpecificationValue builder] mergeFromCodedInputStream:input] build];
}
+ (ProductSpecificationValue*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ProductSpecificationValue*)[[[ProductSpecificationValue builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ProductSpecificationValue_Builder*) builder {
  return [[[ProductSpecificationValue_Builder alloc] init] autorelease];
}
+ (ProductSpecificationValue_Builder*) builderWithPrototype:(ProductSpecificationValue*) prototype {
  return [[ProductSpecificationValue builder] mergeFrom:prototype];
}
- (ProductSpecificationValue_Builder*) builder {
  return [ProductSpecificationValue builder];
}
- (ProductSpecificationValue_Builder*) toBuilder {
  return [ProductSpecificationValue builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"id", [NSNumber numberWithInt:self.id]];
  }
  if (self.hasName) {
    [output appendFormat:@"%@%@: %@\n", indent, @"name", self.name];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[ProductSpecificationValue class]]) {
    return NO;
  }
  ProductSpecificationValue *otherMessage = other;
  return
      self.hasId == otherMessage.hasId &&
      (!self.hasId || self.id == otherMessage.id) &&
      self.hasName == otherMessage.hasName &&
      (!self.hasName || [self.name isEqual:otherMessage.name]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  NSUInteger hashCode = 7;
  if (self.hasId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.id] hash];
  }
  if (self.hasName) {
    hashCode = hashCode * 31 + [self.name hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface ProductSpecificationValue_Builder()
@property (retain) ProductSpecificationValue* result;
@end

@implementation ProductSpecificationValue_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[ProductSpecificationValue alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (ProductSpecificationValue_Builder*) clear {
  self.result = [[[ProductSpecificationValue alloc] init] autorelease];
  return self;
}
- (ProductSpecificationValue_Builder*) clone {
  return [ProductSpecificationValue builderWithPrototype:result];
}
- (ProductSpecificationValue*) defaultInstance {
  return [ProductSpecificationValue defaultInstance];
}
- (ProductSpecificationValue*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (ProductSpecificationValue*) buildPartial {
  ProductSpecificationValue* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (ProductSpecificationValue_Builder*) mergeFrom:(ProductSpecificationValue*) other {
  if (other == [ProductSpecificationValue defaultInstance]) {
    return self;
  }
  if (other.hasId) {
    [self setId:other.id];
  }
  if (other.hasName) {
    [self setName:other.name];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (ProductSpecificationValue_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (ProductSpecificationValue_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setId:[input readInt32]];
        break;
      }
      case 18: {
        [self setName:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasId {
  return result.hasId;
}
- (int32_t) id {
  return result.id;
}
- (ProductSpecificationValue_Builder*) setId:(int32_t) value {
  result.hasId = YES;
  result.id = value;
  return self;
}
- (ProductSpecificationValue_Builder*) clearId {
  result.hasId = NO;
  result.id = 0;
  return self;
}
- (BOOL) hasName {
  return result.hasName;
}
- (NSString*) name {
  return result.name;
}
- (ProductSpecificationValue_Builder*) setName:(NSString*) value {
  result.hasName = YES;
  result.name = value;
  return self;
}
- (ProductSpecificationValue_Builder*) clearName {
  result.hasName = NO;
  result.name = @"";
  return self;
}
@end

