// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "Generic.pb.h"
#import "User.pb.h"

@class AppSetting;
@class AppSetting_Builder;
@class Company;
@class Company_Builder;
@class Department;
@class Department_Builder;
@class Device;
@class Device_Builder;
@class Function;
@class Function_Builder;
@class Location;
@class Location_Builder;
@class PageUser;
@class PageUser_Builder;
@class Pagination;
@class Pagination_Builder;
@class Permission;
@class Permission_Builder;
@class Position;
@class Position_Builder;
@class QchatUserGroup;
@class QchatUserGroup_Builder;
@class SystemSetting;
@class SystemSetting_Builder;
@class User;
@class UserParams;
@class UserParams_Builder;
@class User_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface QchatRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface QchatUserGroup : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasName_:1;
  BOOL hasComment_:1;
  BOOL hasCompany_:1;
  BOOL hasCreateUser_:1;
  int32_t id;
  NSString* name;
  NSString* comment;
  Company* company;
  User* createUser;
  PBAppendableArray * usersArray;
}
- (BOOL) hasId;
- (BOOL) hasName;
- (BOOL) hasComment;
- (BOOL) hasCompany;
- (BOOL) hasCreateUser;
@property (readonly) int32_t id;
@property (readonly, retain) PBArray * users;
@property (readonly, retain) NSString* name;
@property (readonly, retain) NSString* comment;
@property (readonly, retain) Company* company;
@property (readonly, retain) User* createUser;
- (User*)usersAtIndex:(NSUInteger)index;

+ (QchatUserGroup*) defaultInstance;
- (QchatUserGroup*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (QchatUserGroup_Builder*) builder;
+ (QchatUserGroup_Builder*) builder;
+ (QchatUserGroup_Builder*) builderWithPrototype:(QchatUserGroup*) prototype;
- (QchatUserGroup_Builder*) toBuilder;

+ (QchatUserGroup*) parseFromData:(NSData*) data;
+ (QchatUserGroup*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (QchatUserGroup*) parseFromInputStream:(NSInputStream*) input;
+ (QchatUserGroup*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (QchatUserGroup*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (QchatUserGroup*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface QchatUserGroup_Builder : PBGeneratedMessage_Builder {
@private
  QchatUserGroup* result;
}

- (QchatUserGroup*) defaultInstance;

- (QchatUserGroup_Builder*) clear;
- (QchatUserGroup_Builder*) clone;

- (QchatUserGroup*) build;
- (QchatUserGroup*) buildPartial;

- (QchatUserGroup_Builder*) mergeFrom:(QchatUserGroup*) other;
- (QchatUserGroup_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (QchatUserGroup_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (int32_t) id;
- (QchatUserGroup_Builder*) setId:(int32_t) value;
- (QchatUserGroup_Builder*) clearId;

- (PBAppendableArray *)users;
- (User*)usersAtIndex:(NSUInteger)index;
- (QchatUserGroup_Builder *)addUsers:(User*)value;
- (QchatUserGroup_Builder *)setUsersArray:(NSArray *)array;
- (QchatUserGroup_Builder *)setUsersValues:(const User* *)values count:(NSUInteger)count;
- (QchatUserGroup_Builder *)clearUsers;

- (BOOL) hasName;
- (NSString*) name;
- (QchatUserGroup_Builder*) setName:(NSString*) value;
- (QchatUserGroup_Builder*) clearName;

- (BOOL) hasComment;
- (NSString*) comment;
- (QchatUserGroup_Builder*) setComment:(NSString*) value;
- (QchatUserGroup_Builder*) clearComment;

- (BOOL) hasCompany;
- (Company*) company;
- (QchatUserGroup_Builder*) setCompany:(Company*) value;
- (QchatUserGroup_Builder*) setCompanyBuilder:(Company_Builder*) builderForValue;
- (QchatUserGroup_Builder*) mergeCompany:(Company*) value;
- (QchatUserGroup_Builder*) clearCompany;

- (BOOL) hasCreateUser;
- (User*) createUser;
- (QchatUserGroup_Builder*) setCreateUser:(User*) value;
- (QchatUserGroup_Builder*) setCreateUserBuilder:(User_Builder*) builderForValue;
- (QchatUserGroup_Builder*) mergeCreateUser:(User*) value;
- (QchatUserGroup_Builder*) clearCreateUser;
@end

