// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "Generic.pb.h"
#import "User.pb.h"
#import "Product.pb.h"
#import "Customer.pb.h"

@class AppSetting;
@class AppSetting_Builder;
@class Company;
@class Company_Builder;
@class Contact;
@class Contact_Builder;
@class Customer;
@class CustomerCategory;
@class CustomerCategory_Builder;
@class CustomerParams;
@class CustomerParams_Builder;
@class Customer_Builder;
@class Department;
@class Department_Builder;
@class Device;
@class Device_Builder;
@class Function;
@class Function_Builder;
@class Location;
@class Location_Builder;
@class PageCustomer;
@class PageCustomer_Builder;
@class PageSaleGoods;
@class PageSaleGoods_Builder;
@class PageUser;
@class PageUser_Builder;
@class Pagination;
@class Pagination_Builder;
@class Permission;
@class Permission_Builder;
@class Position;
@class Position_Builder;
@class Product;
@class ProductCategory;
@class ProductCategory_Builder;
@class Product_Builder;
@class SaleGoods;
@class SaleGoodsParams;
@class SaleGoodsParams_Builder;
@class SaleGoods_Builder;
@class SystemSetting;
@class SystemSetting_Builder;
@class User;
@class UserParams;
@class UserParams_Builder;
@class User_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface SaleRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface SaleGoods : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasStates_:1;
  BOOL hasComment_:1;
  BOOL hasCreateDate_:1;
  BOOL hasUser_:1;
  BOOL hasCustomer_:1;
  BOOL hasLocation_:1;
  int32_t id;
  int32_t states;
  NSString* comment;
  NSString* createDate;
  User* user;
  Customer* customer;
  Location* location;
  PBAppendableArray * productsArray;
}
- (BOOL) hasUser;
- (BOOL) hasId;
- (BOOL) hasCustomer;
- (BOOL) hasStates;
- (BOOL) hasComment;
- (BOOL) hasLocation;
- (BOOL) hasCreateDate;
@property (readonly, retain) User* user;
@property (readonly) int32_t id;
@property (readonly, retain) Customer* customer;
@property (readonly) int32_t states;
@property (readonly, retain) NSString* comment;
@property (readonly, retain) Location* location;
@property (readonly, retain) NSString* createDate;
@property (readonly, retain) PBArray * products;
- (Product*)productsAtIndex:(NSUInteger)index;

+ (SaleGoods*) defaultInstance;
- (SaleGoods*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SaleGoods_Builder*) builder;
+ (SaleGoods_Builder*) builder;
+ (SaleGoods_Builder*) builderWithPrototype:(SaleGoods*) prototype;
- (SaleGoods_Builder*) toBuilder;

+ (SaleGoods*) parseFromData:(NSData*) data;
+ (SaleGoods*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SaleGoods*) parseFromInputStream:(NSInputStream*) input;
+ (SaleGoods*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SaleGoods*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SaleGoods*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SaleGoods_Builder : PBGeneratedMessage_Builder {
@private
  SaleGoods* result;
}

- (SaleGoods*) defaultInstance;

- (SaleGoods_Builder*) clear;
- (SaleGoods_Builder*) clone;

- (SaleGoods*) build;
- (SaleGoods*) buildPartial;

- (SaleGoods_Builder*) mergeFrom:(SaleGoods*) other;
- (SaleGoods_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SaleGoods_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUser;
- (User*) user;
- (SaleGoods_Builder*) setUser:(User*) value;
- (SaleGoods_Builder*) setUserBuilder:(User_Builder*) builderForValue;
- (SaleGoods_Builder*) mergeUser:(User*) value;
- (SaleGoods_Builder*) clearUser;

- (BOOL) hasId;
- (int32_t) id;
- (SaleGoods_Builder*) setId:(int32_t) value;
- (SaleGoods_Builder*) clearId;

- (BOOL) hasCustomer;
- (Customer*) customer;
- (SaleGoods_Builder*) setCustomer:(Customer*) value;
- (SaleGoods_Builder*) setCustomerBuilder:(Customer_Builder*) builderForValue;
- (SaleGoods_Builder*) mergeCustomer:(Customer*) value;
- (SaleGoods_Builder*) clearCustomer;

- (BOOL) hasStates;
- (int32_t) states;
- (SaleGoods_Builder*) setStates:(int32_t) value;
- (SaleGoods_Builder*) clearStates;

- (BOOL) hasComment;
- (NSString*) comment;
- (SaleGoods_Builder*) setComment:(NSString*) value;
- (SaleGoods_Builder*) clearComment;

- (BOOL) hasLocation;
- (Location*) location;
- (SaleGoods_Builder*) setLocation:(Location*) value;
- (SaleGoods_Builder*) setLocationBuilder:(Location_Builder*) builderForValue;
- (SaleGoods_Builder*) mergeLocation:(Location*) value;
- (SaleGoods_Builder*) clearLocation;

- (BOOL) hasCreateDate;
- (NSString*) createDate;
- (SaleGoods_Builder*) setCreateDate:(NSString*) value;
- (SaleGoods_Builder*) clearCreateDate;

- (PBAppendableArray *)products;
- (Product*)productsAtIndex:(NSUInteger)index;
- (SaleGoods_Builder *)addProducts:(Product*)value;
- (SaleGoods_Builder *)setProductsArray:(NSArray *)array;
- (SaleGoods_Builder *)setProductsValues:(const Product* *)values count:(NSUInteger)count;
- (SaleGoods_Builder *)clearProducts;
@end

@interface PageSaleGoods : PBGeneratedMessage {
@private
  BOOL hasPage_:1;
  Pagination* page;
  PBAppendableArray * saleGoodsArray;
}
- (BOOL) hasPage;
@property (readonly, retain) Pagination* page;
@property (readonly, retain) PBArray * saleGoods;
- (SaleGoods*)saleGoodsAtIndex:(NSUInteger)index;

+ (PageSaleGoods*) defaultInstance;
- (PageSaleGoods*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PageSaleGoods_Builder*) builder;
+ (PageSaleGoods_Builder*) builder;
+ (PageSaleGoods_Builder*) builderWithPrototype:(PageSaleGoods*) prototype;
- (PageSaleGoods_Builder*) toBuilder;

+ (PageSaleGoods*) parseFromData:(NSData*) data;
+ (PageSaleGoods*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PageSaleGoods*) parseFromInputStream:(NSInputStream*) input;
+ (PageSaleGoods*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PageSaleGoods*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PageSaleGoods*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PageSaleGoods_Builder : PBGeneratedMessage_Builder {
@private
  PageSaleGoods* result;
}

- (PageSaleGoods*) defaultInstance;

- (PageSaleGoods_Builder*) clear;
- (PageSaleGoods_Builder*) clone;

- (PageSaleGoods*) build;
- (PageSaleGoods*) buildPartial;

- (PageSaleGoods_Builder*) mergeFrom:(PageSaleGoods*) other;
- (PageSaleGoods_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PageSaleGoods_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPage;
- (Pagination*) page;
- (PageSaleGoods_Builder*) setPage:(Pagination*) value;
- (PageSaleGoods_Builder*) setPageBuilder:(Pagination_Builder*) builderForValue;
- (PageSaleGoods_Builder*) mergePage:(Pagination*) value;
- (PageSaleGoods_Builder*) clearPage;

- (PBAppendableArray *)saleGoods;
- (SaleGoods*)saleGoodsAtIndex:(NSUInteger)index;
- (PageSaleGoods_Builder *)addSaleGoods:(SaleGoods*)value;
- (PageSaleGoods_Builder *)setSaleGoodsArray:(NSArray *)array;
- (PageSaleGoods_Builder *)setSaleGoodsValues:(const SaleGoods* *)values count:(NSUInteger)count;
- (PageSaleGoods_Builder *)clearSaleGoods;
@end

@interface SaleGoodsParams : PBGeneratedMessage {
@private
  BOOL hasPage_:1;
  BOOL hasStartDate_:1;
  BOOL hasEndDate_:1;
  int32_t page;
  NSString* startDate;
  NSString* endDate;
  PBAppendableArray * usersArray;
  PBAppendableArray * customerCategoryArray;
  PBAppendableArray * customersArray;
  PBAppendableArray * departmentsArray;
  PBAppendableArray * companiesArray;
}
- (BOOL) hasPage;
- (BOOL) hasStartDate;
- (BOOL) hasEndDate;
@property (readonly) int32_t page;
@property (readonly, retain) PBArray * users;
@property (readonly, retain) PBArray * customerCategory;
@property (readonly, retain) PBArray * customers;
@property (readonly, retain) PBArray * departments;
@property (readonly, retain) PBArray * companies;
@property (readonly, retain) NSString* startDate;
@property (readonly, retain) NSString* endDate;
- (User*)usersAtIndex:(NSUInteger)index;
- (CustomerCategory*)customerCategoryAtIndex:(NSUInteger)index;
- (Customer*)customersAtIndex:(NSUInteger)index;
- (Department*)departmentsAtIndex:(NSUInteger)index;
- (Company*)companiesAtIndex:(NSUInteger)index;

+ (SaleGoodsParams*) defaultInstance;
- (SaleGoodsParams*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SaleGoodsParams_Builder*) builder;
+ (SaleGoodsParams_Builder*) builder;
+ (SaleGoodsParams_Builder*) builderWithPrototype:(SaleGoodsParams*) prototype;
- (SaleGoodsParams_Builder*) toBuilder;

+ (SaleGoodsParams*) parseFromData:(NSData*) data;
+ (SaleGoodsParams*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SaleGoodsParams*) parseFromInputStream:(NSInputStream*) input;
+ (SaleGoodsParams*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SaleGoodsParams*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SaleGoodsParams*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SaleGoodsParams_Builder : PBGeneratedMessage_Builder {
@private
  SaleGoodsParams* result;
}

- (SaleGoodsParams*) defaultInstance;

- (SaleGoodsParams_Builder*) clear;
- (SaleGoodsParams_Builder*) clone;

- (SaleGoodsParams*) build;
- (SaleGoodsParams*) buildPartial;

- (SaleGoodsParams_Builder*) mergeFrom:(SaleGoodsParams*) other;
- (SaleGoodsParams_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SaleGoodsParams_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPage;
- (int32_t) page;
- (SaleGoodsParams_Builder*) setPage:(int32_t) value;
- (SaleGoodsParams_Builder*) clearPage;

- (PBAppendableArray *)users;
- (User*)usersAtIndex:(NSUInteger)index;
- (SaleGoodsParams_Builder *)addUsers:(User*)value;
- (SaleGoodsParams_Builder *)setUsersArray:(NSArray *)array;
- (SaleGoodsParams_Builder *)setUsersValues:(const User* *)values count:(NSUInteger)count;
- (SaleGoodsParams_Builder *)clearUsers;

- (PBAppendableArray *)customerCategory;
- (CustomerCategory*)customerCategoryAtIndex:(NSUInteger)index;
- (SaleGoodsParams_Builder *)addCustomerCategory:(CustomerCategory*)value;
- (SaleGoodsParams_Builder *)setCustomerCategoryArray:(NSArray *)array;
- (SaleGoodsParams_Builder *)setCustomerCategoryValues:(const CustomerCategory* *)values count:(NSUInteger)count;
- (SaleGoodsParams_Builder *)clearCustomerCategory;

- (PBAppendableArray *)customers;
- (Customer*)customersAtIndex:(NSUInteger)index;
- (SaleGoodsParams_Builder *)addCustomers:(Customer*)value;
- (SaleGoodsParams_Builder *)setCustomersArray:(NSArray *)array;
- (SaleGoodsParams_Builder *)setCustomersValues:(const Customer* *)values count:(NSUInteger)count;
- (SaleGoodsParams_Builder *)clearCustomers;

- (PBAppendableArray *)departments;
- (Department*)departmentsAtIndex:(NSUInteger)index;
- (SaleGoodsParams_Builder *)addDepartments:(Department*)value;
- (SaleGoodsParams_Builder *)setDepartmentsArray:(NSArray *)array;
- (SaleGoodsParams_Builder *)setDepartmentsValues:(const Department* *)values count:(NSUInteger)count;
- (SaleGoodsParams_Builder *)clearDepartments;

- (PBAppendableArray *)companies;
- (Company*)companiesAtIndex:(NSUInteger)index;
- (SaleGoodsParams_Builder *)addCompanies:(Company*)value;
- (SaleGoodsParams_Builder *)setCompaniesArray:(NSArray *)array;
- (SaleGoodsParams_Builder *)setCompaniesValues:(const Company* *)values count:(NSUInteger)count;
- (SaleGoodsParams_Builder *)clearCompanies;

- (BOOL) hasStartDate;
- (NSString*) startDate;
- (SaleGoodsParams_Builder*) setStartDate:(NSString*) value;
- (SaleGoodsParams_Builder*) clearStartDate;

- (BOOL) hasEndDate;
- (NSString*) endDate;
- (SaleGoodsParams_Builder*) setEndDate:(NSString*) value;
- (SaleGoodsParams_Builder*) clearEndDate;
@end

